// ── Imposter word bank ──────────────────────────────────
export const imposterWordBank: Record<string, string[]> = {
  animals: ["Dog", "Cat", "Elephant", "Lion", "Tiger", "Bear", "Giraffe", "Zebra", "Kangaroo", "Penguin", "Horse", "Wolf", "Fox", "Panda", "Rabbit", "Koala", "Cheetah", "Dolphin", "Monkey", "Owl"],
  moviesAndShows: ["Breaking Bad", "Stranger Things", "The Office", "Game of Thrones", "Friends", "The Mandalorian", "The Witcher", "Better Call Saul", "Avatar", "Top Gun", "John Wick", "Oppenheimer", "Dune", "Interstellar", "Spider-Man", "Avengers", "The Batman", "Barbie", "The Boys", "Squid Game"],
  disneyAndPixar: ["Frozen", "Toy Story", "Moana", "The Lion King", "Encanto", "Finding Nemo", "Coco", "Ratatouille", "Up", "Zootopia", "Inside Out", "Brave", "Cars", "Monsters Inc", "Turning Red", "Aladdin", "Beauty and the Beast", "Mulan", "Big Hero 6", "WALL-E"],
  fpsGames: ["Call of Duty", "Valorant", "Overwatch", "Counter-Strike", "Rainbow Six Siege", "Battlefield", "Apex Legends", "Destiny 2", "Halo", "PUBG", "Escape from Tarkov", "Fortnite", "Team Fortress 2", "DOOM", "Warframe"],
  otherGames: ["Minecraft", "Roblox", "League of Legends", "Among Us", "Genshin Impact", "Elden Ring", "Baldur's Gate 3", "The Sims", "Animal Crossing", "Grand Theft Auto V", "Red Dead Redemption 2", "Fall Guys", "Rocket League", "Sea of Thieves", "Cyberpunk 2077"],
  food: ["Pizza", "Burger", "Pasta", "Sushi", "Taco", "Steak", "Chicken Wings", "Salad", "Fried Rice", "Ramen", "Lasagna", "Burrito", "Sandwich", "Pancakes", "Hot Dog", "Cheesecake", "Nachos", "Dumplings", "Curry", "French Fries"],
  drinks: ["Coca-Cola", "Pepsi", "Coffee", "Tea", "Lemonade", "Milkshake", "Smoothie", "Orange Juice", "Sprite", "Dr Pepper", "Mountain Dew", "Iced Coffee", "Energy Drink", "Red Bull", "Gatorade", "Hot Chocolate", "Latte", "Root Beer", "Apple Juice", "Mojito"],
  restaurants: ["McDonald's", "Starbucks", "Chick-fil-A", "Taco Bell", "Subway", "KFC", "Pizza Hut", "Wendy's", "Burger King", "Domino's", "Chipotle", "Panda Express", "Panera Bread", "Five Guys", "Dunkin'", "Olive Garden", "Buffalo Wild Wings", "Sonic", "Arby's", "Popeyes"],
  carBrands: ["Toyota", "Ford", "Chevrolet", "Honda", "BMW", "Mercedes-Benz", "Audi", "Tesla", "Volkswagen", "Nissan", "Jeep", "Hyundai", "Kia", "Lexus", "Subaru", "Porsche", "Mazda", "Dodge", "Ferrari", "Lamborghini"],
  luxuryBrands: ["Gucci", "Louis Vuitton", "Chanel", "Prada", "Rolex", "Cartier", "Burberry", "Dior", "Balenciaga", "Versace", "Tiffany", "Fendi", "Givenchy", "Valentino", "Armani", "Tom Ford", "Moncler", "Hermes", "YSL", "Bvlgari"],
  sports: ["Soccer", "Basketball", "Baseball", "Football", "Tennis", "Golf", "Hockey", "Wrestling", "Swimming", "Boxing", "Skateboarding", "Cycling", "Cricket", "Table Tennis", "Volleyball", "Rugby", "Lacrosse", "Badminton", "Surfing", "Skiing"],
  celebrities: ["Taylor Swift", "Dwayne Johnson", "Selena Gomez", "Kim Kardashian", "Lionel Messi", "Beyoncé", "Cristiano Ronaldo", "Drake", "LeBron James", "Ariana Grande", "Zendaya", "Billie Eilish", "Elon Musk", "Rihanna", "Tom Holland", "Emma Watson", "Chris Hemsworth", "Shakira", "Travis Scott", "Bad Bunny"],
  countries: ["United States", "Canada", "Mexico", "United Kingdom", "France", "Germany", "Italy", "Spain", "Japan", "China", "Australia", "India", "Brazil", "Russia", "South Korea", "South Africa", "Netherlands", "Sweden", "Switzerland", "New Zealand"],
  cities: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Miami", "Atlanta", "Dallas", "Seattle", "San Francisco", "Boston", "Las Vegas", "Orlando", "San Diego", "Denver", "Philadelphia", "Austin", "Portland", "Washington DC", "Detroit"],
  minecraftMobs: ["Creeper", "Zombie", "Skeleton", "Enderman", "Spider", "Villager", "Witch", "Slime", "Blaze", "Ghast", "Piglin", "Wither Skeleton", "Iron Golem", "Pillager", "Drowned", "Warden", "Husk", "Stray", "Bee", "Axolotl"]
};

export const imposterCategories = Object.keys(imposterWordBank) as Array<keyof typeof imposterWordBank>;

export const imposterCategoryLabels: Record<string, string> = {
  animals: "Animals",
  moviesAndShows: "Movies & Shows",
  disneyAndPixar: "Disney & Pixar",
  fpsGames: "FPS Games",
  otherGames: "Other Games",
  food: "Food",
  drinks: "Drinks",
  restaurants: "Restaurants",
  carBrands: "Car Brands",
  luxuryBrands: "Luxury Brands",
  sports: "Sports",
  celebrities: "Celebrities",
  countries: "Countries",
  cities: "Cities",
  minecraftMobs: "Minecraft Mobs"
};

// ── Chain Reaction word bank ────────────────────────────
// Each chain is an array of words where adjacent pairs form a common compound phrase.
export const chainWordBank: string[][] = [
  ["FIRE", "TRUCK", "STOP", "SIGN", "LANGUAGE"],
  ["SUN", "FLOWER", "POT", "LUCK", "CHARM"],
  ["BOOK", "WORM", "HOLE", "PUNCH", "LINE"],
  ["SNOW", "BALL", "PARK", "BENCH", "PRESS"],
  ["RAIN", "BOW", "TIE", "BREAK", "FAST"],
  ["STAR", "FISH", "BOWL", "CUT", "BACK"],
  ["SAND", "CASTLE", "ROCK", "BAND", "WIDTH"],
  ["DOOR", "BELL", "TOWER", "BRIDGE", "WORK"],
  ["FOOT", "BALL", "ROOM", "MATE", "SHIP"],
  ["HORSE", "SHOE", "LACE", "WORK", "SHOP"],
  ["WATER", "FALL", "BACK", "BONE", "FIRE"],
  ["BLACK", "BOARD", "GAME", "PLAN", "TREE"],
  ["TREE", "HOUSE", "WIFE", "TIME", "ZONE"],
  ["NIGHT", "MARE", "TAIL", "GATE", "CRASH"],
  ["BLOOD", "HOUND", "DOG", "HOUSE", "HOLD"],
  ["KEY", "BOARD", "WALK", "WAY", "SIDE"],
  ["GOLD", "MINE", "FIELD", "GOAL", "POST"],
  ["SEA", "SHELL", "FISH", "TANK", "TOP"],
  ["TOOTH", "BRUSH", "FIRE", "WORK", "FORCE"],
  ["HAND", "SHAKE", "DOWN", "HILL", "SIDE"],
  ["AIR", "PORT", "HOLE", "SALE", "PRICE"],
  ["HAIR", "CUT", "THROAT", "SONG", "BIRD"],
  ["HEAD", "BAND", "STAND", "STILL", "LIFE"],
  ["MOON", "LIGHT", "HOUSE", "BOAT", "LOAD"],
  ["EARTH", "WORM", "WOOD", "LAND", "MARK"],
  ["NEWS", "PAPER", "WEIGHT", "LIFT", "OFF"],
  ["EYE", "BROW", "BEAT", "DOWN", "POUR"],
  ["HEART", "BEAT", "BOX", "CAR", "POOL"],
  ["ROAD", "BLOCK", "CHAIN", "MAIL", "BOX"],
  ["BED", "ROOM", "SERVICE", "CHARGE", "BACK"],
  // 6-word chains
  ["FIRE", "SIDE", "WALK", "WAY", "POINT", "GUARD"],
  ["RAIN", "COAT", "RACK", "BALL", "GAME", "PLAN"],
  ["SNOW", "DRIFT", "WOOD", "WORK", "SHOP", "LIFT"],
  ["DAY", "LIGHT", "WEIGHT", "LOSS", "LEADER", "BOARD"],
  ["SUN", "BURN", "MARK", "DOWN", "TOWN", "HOUSE"],
  ["BOOK", "MARK", "TIME", "LINE", "BACK", "FIRE"],
  ["FOOT", "NOTE", "BOOK", "CASE", "WORK", "BENCH"],
  ["OVER", "NIGHT", "FALL", "BACK", "PACK", "HORSE"],
  ["HOME", "SICK", "BED", "BUG", "SPRAY", "PAINT"],
  ["CROSS", "BOW", "STRING", "BEAN", "BAG", "PIPE"],
  // 7-word chains
  ["BLACK", "BIRD", "HOUSE", "WIFE", "TIME", "ZONE", "OUT"],
  ["WATER", "PROOF", "READ", "BACK", "BONE", "HEAD", "BAND"],
  ["HAND", "STAND", "STILL", "LIFE", "TIME", "LINE", "BACK"],
  ["NIGHT", "CLUB", "HOUSE", "WORK", "LOAD", "STAR", "LIGHT"],
  ["GOLD", "FISH", "BOWL", "CUT", "BACK", "DOOR", "BELL"],
  ["SEA", "HORSE", "SHOE", "HORN", "BILL", "BOARD", "ROOM"],
  ["HAIR", "PIN", "POINT", "GUARD", "RAIL", "ROAD", "BLOCK"],
  ["HEAD", "LINE", "BACK", "YARD", "STICK", "BALL", "PARK"],
  ["MOON", "SHINE", "COAT", "TAIL", "SPIN", "WHEEL", "CHAIR"],
  ["EARTH", "BOUND", "LESS", "WORK", "BENCH", "MARK", "DOWN"],
  // 8-word chains
  ["RAIN", "DROP", "KICK", "BACK", "FIRE", "SIDE", "WALK", "WAY"],
  ["SNOW", "BALL", "PARK", "LAND", "MARK", "DOWN", "HILL", "SIDE"],
  ["FIRE", "PLACE", "KICK", "BACK", "PACK", "HORSE", "PLAY", "GROUND"],
  ["NIGHT", "FALL", "BACK", "BONE", "HEAD", "BAND", "WAGON", "WHEEL"],
  ["BOOK", "SHELF", "LIFE", "BOAT", "HOUSE", "WORK", "LOAD", "STAR"],
  // 9-word chains
  ["RAIN", "DROP", "KICK", "BACK", "FIRE", "SIDE", "WALK", "WAY", "POINT"],
  ["SNOW", "BALL", "PARK", "LAND", "MARK", "DOWN", "HILL", "SIDE", "LINE"],
  ["NIGHT", "FALL", "BACK", "BONE", "HEAD", "BAND", "WAGON", "WHEEL", "CHAIR"],
  ["TIME", "SHARE", "CROP", "LAND", "SLIDE", "SHOW", "BOAT", "HOUSE", "WIFE"],
  ["HAND", "SHAKE", "DOWN", "HILL", "SIDE", "KICK", "BACK", "BONE", "HEAD"],
  // 10-word chains
  ["RAIN", "DROP", "KICK", "BACK", "FIRE", "SIDE", "WALK", "WAY", "POINT", "GUARD"],
  ["SNOW", "BALL", "PARK", "LAND", "MARK", "DOWN", "HILL", "SIDE", "LINE", "BACK"],
  ["NIGHT", "FALL", "BACK", "BONE", "HEAD", "BAND", "WAGON", "WHEEL", "CHAIR", "MAN"],
  ["TIME", "SHARE", "CROP", "LAND", "SLIDE", "SHOW", "BOAT", "HOUSE", "WORK", "LOAD"],
  ["HAND", "SHAKE", "DOWN", "HILL", "SIDE", "KICK", "BACK", "BONE", "HEAD", "BAND"],
];

// ── Password word bank ──────────────────────────────────
// Common nouns that work well with one-word clues
export const passwordWordBank = [
  "Apple", "Bridge", "Camera", "Dragon", "Eagle", "Forest", "Guitar", "Hammer",
  "Island", "Jacket", "Kite", "Ladder", "Mirror", "Needle", "Ocean", "Pillow",
  "Queen", "Rocket", "Shadow", "Tunnel", "Umbrella", "Volcano", "Window", "Anchor",
  "Balloon", "Castle", "Diamond", "Engine", "Feather", "Globe", "Helmet", "Igloo",
  "Jungle", "Kettle", "Lantern", "Mountain", "Noodle", "Oyster", "Penguin", "Puzzle",
  "Rainbow", "Scarecrow", "Tomato", "Unicorn", "Violin", "Wizard", "Blanket", "Candle",
  "Desert", "Fossil", "Garage", "Harvest", "Iceberg", "Juggler", "Kitten", "Library",
  "Magnet", "Napkin", "Orchid", "Parrot", "Quilt", "Robot", "Saddle", "Tornado",
  "Thunder", "Velvet", "Waffle", "Basket", "Cactus", "Dolphin", "Emerald", "Falcon",
  "Ghost", "Honey", "Ivory", "Jigsaw", "Koala", "Lemon", "Marble", "Nugget",
  "Otter", "Pirate", "Rabbit", "Sailor", "Tiger", "Vampire", "Walrus", "Cookie",
  "Compass", "Crystal", "Dungeon", "Eclipse", "Flame", "Goblin", "Harpoon", "Sphinx",
  "Treasure", "Trident", "Phantom", "Serpent", "Beacon", "Blizzard", "Canyon", "Comet",
  "Dagger", "Fortress", "Glacier", "Labyrinth", "Meteor", "Oasis", "Palace", "Raven",
  "Scepter", "Tempest", "Vortex", "Whistle", "Zombie", "Arrow", "Barrel", "Circus",
  "Curtain", "Fountain", "Garlic", "Hammock", "Insect", "Jewel", "Knot", "Lotus",
  "Mango", "Orbit", "Pebble", "Riddle", "Sunset", "Trophy", "Voyage", "Wrench",
];
