// ── Imposter word bank ──────────────────────────────────
export const imposterWordBank: Record<string, string[]> = {
  animals: ["Dog", "Cat", "Elephant", "Lion", "Tiger", "Bear", "Giraffe", "Zebra", "Kangaroo", "Penguin", "Horse", "Wolf", "Fox", "Panda", "Rabbit", "Koala", "Cheetah", "Dolphin", "Monkey", "Owl"],
  moviesAndShows: ["Breaking Bad", "Stranger Things", "The Office", "Game of Thrones", "Friends", "The Mandalorian", "The Witcher", "Better Call Saul", "Avatar", "Top Gun", "John Wick", "Oppenheimer", "Dune", "Interstellar", "Spider-Man", "Avengers", "The Batman", "Barbie", "The Boys", "Squid Game"],
  disneyAndPixar: ["Frozen", "Toy Story", "Moana", "The Lion King", "Encanto", "Finding Nemo", "Coco", "Ratatouille", "Up", "Zootopia", "Inside Out", "Brave", "Cars", "Monsters Inc", "Turning Red", "Aladdin", "Beauty and the Beast", "Mulan", "Big Hero 6", "WALL-E"],
  fpsGames: ["Call of Duty", "Valorant", "Overwatch", "Counter-Strike", "Rainbow Six Siege", "Battlefield", "Apex Legends", "Destiny 2", "Halo", "PUBG", "Escape from Tarkov", "Fortnite", "Team Fortress 2", "DOOM", "Warframe"],
  otherGames: ["Minecraft", "Roblox", "League of Legends", "Among Us", "Genshin Impact", "Elden Ring", "Baldur's Gate 3", "The Sims", "Animal Crossing", "Grand Theft Auto V", "Red Dead Redemption 2", "Fall Guys", "Rocket League", "Sea of Thieves", "Cyberpunk 2077"],
  food: ["Pizza", "Burger", "Pasta", "Sushi", "Taco", "Steak", "Chicken Wings", "Salad", "Fried Rice", "Ramen", "Lasagna", "Burrito", "Sandwich", "Pancakes", "Hot Dog", "Cheesecake", "Nachos", "Dumplings", "Curry", "French Fries"],
  drinks: ["Coca-Cola", "Pepsi", "Coffee", "Tea", "Lemonade", "Milkshake", "Smoothie", "Orange Juice", "Sprite", "Dr Pepper", "Mountain Dew", "Iced Coffee", "Energy Drink", "Red Bull", "Gatorade", "Hot Chocolate", "Latte", "Root Beer", "Apple Juice", "Mojito"],
  restaurants: ["McDonald's", "Starbucks", "Chick-fil-A", "Taco Bell", "Subway", "KFC", "Pizza Hut", "Wendy's", "Burger King", "Domino's", "Chipotle", "Panda Express", "Panera Bread", "Five Guys", "Dunkin'", "Olive Garden", "Buffalo Wild Wings", "Sonic", "Arby's", "Popeyes"],
  carBrands: ["Toyota", "Ford", "Chevrolet", "Honda", "BMW", "Mercedes-Benz", "Audi", "Tesla", "Volkswagen", "Nissan", "Jeep", "Hyundai", "Kia", "Lexus", "Subaru", "Porsche", "Mazda", "Dodge", "Ferrari", "Lamborghini"],
  luxuryBrands: ["Gucci", "Louis Vuitton", "Chanel", "Prada", "Rolex", "Cartier", "Burberry", "Dior", "Balenciaga", "Versace", "Tiffany", "Fendi", "Givenchy", "Valentino", "Armani", "Tom Ford", "Moncler", "Hermes", "YSL", "Bvlgari"],
  sports: ["Soccer", "Basketball", "Baseball", "Football", "Tennis", "Golf", "Hockey", "Wrestling", "Swimming", "Boxing", "Skateboarding", "Cycling", "Cricket", "Table Tennis", "Volleyball", "Rugby", "Lacrosse", "Badminton", "Surfing", "Skiing"],
  celebrities: ["Taylor Swift", "Dwayne Johnson", "Selena Gomez", "Kim Kardashian", "Lionel Messi", "Beyoncé", "Cristiano Ronaldo", "Drake", "LeBron James", "Ariana Grande", "Zendaya", "Billie Eilish", "Elon Musk", "Rihanna", "Tom Holland", "Emma Watson", "Chris Hemsworth", "Shakira", "Travis Scott", "Bad Bunny"],
  countries: ["United States", "Canada", "Mexico", "United Kingdom", "France", "Germany", "Italy", "Spain", "Japan", "China", "Australia", "India", "Brazil", "Russia", "South Korea", "South Africa", "Netherlands", "Sweden", "Switzerland", "New Zealand"],
  cities: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Miami", "Atlanta", "Dallas", "Seattle", "San Francisco", "Boston", "Las Vegas", "Orlando", "San Diego", "Denver", "Philadelphia", "Austin", "Portland", "Washington DC", "Detroit"],
  minecraftMobs: ["Creeper", "Zombie", "Skeleton", "Enderman", "Spider", "Villager", "Witch", "Slime", "Blaze", "Ghast", "Piglin", "Wither Skeleton", "Iron Golem", "Pillager", "Drowned", "Warden", "Husk", "Stray", "Bee", "Axolotl"]
};

// ── Shared category labels (used by all games) ─────────
export const gameCategoryLabels: Record<string, string> = {
  animals: "Animals",
  moviesAndShows: "Movies & Shows",
  disneyAndPixar: "Disney & Pixar",
  fpsGames: "FPS Games",
  otherGames: "Other Games",
  food: "Food",
  drinks: "Drinks",
  restaurants: "Restaurants",
  carBrands: "Car Brands",
  luxuryBrands: "Luxury Brands",
  sports: "Sports",
  celebrities: "Celebrities",
  countries: "Countries",
  cities: "Cities",
  minecraftMobs: "Minecraft Mobs"
};

export const gameCategories = Object.keys(gameCategoryLabels);

export const imposterCategories = Object.keys(imposterWordBank) as Array<keyof typeof imposterWordBank>;

export const imposterCategoryLabels: Record<string, string> = { ...gameCategoryLabels };

// ── Chain Reaction word bank (categorized) ──────────────
// Each chain is an array of words where adjacent pairs form a compound/associative phrase, themed around the category.
export const chainWordBank: Record<string, string[][]> = {
  animals: [
    // 5-word chains
    ["DOG", "HOUSE", "CAT", "FISH", "BOWL"],
    ["HORSE", "SHOE", "HORN", "BILL", "BIRD"],
    ["BEAR", "TRAP", "DOOR", "BELL", "HOP"],
    ["WOLF", "PACK", "HORSE", "TAIL", "GATE"],
    ["FOX", "HUNT", "DOG", "BONE", "DRY"],
    ["FISH", "TANK", "TOP", "DOG", "HOUSE"],
    ["CAT", "NAP", "TIME", "FLY", "TRAP"],
    ["BULL", "FROG", "MAN", "BEAR", "SKIN"],
    ["ANT", "HILL", "TOP", "CAT", "WALK"],
    ["BEE", "HIVE", "MIND", "SET", "BACK"],
    ["SNAKE", "BITE", "MARK", "BIRD", "CAGE"],
    ["CROW", "BAR", "FLY", "FISH", "HOOK"],
    // 6-word chains
    ["DOG", "WATCH", "BIRD", "HOUSE", "CAT", "NAP"],
    ["HORSE", "PLAY", "GROUND", "HOG", "WASH", "BEAR"],
    ["SPIDER", "WEB", "FOOT", "PRINT", "WOLF", "PACK"],
    ["BULL", "RING", "WORM", "HOLE", "FISH", "POND"],
    ["CAT", "FISH", "BOWL", "CUT", "WORM", "HOLE"],
    ["DOG", "HOUSE", "CAT", "FISH", "BOWL", "CUT"],
    ["HORSE", "SHOE", "HORN", "BILL", "BIRD", "HOUSE"],
    ["BEAR", "TRAP", "DOOR", "BELL", "HOP", "SCOTCH"],
    ["WOLF", "PACK", "HORSE", "TAIL", "GATE", "WAY"],
    ["FOX", "HUNT", "DOG", "BONE", "DRY", "DOCK"],
    // 7-word chains
    ["DOG", "HOUSE", "FLY", "TRAP", "DOOR", "MOUSE", "PAD"],
    ["FISH", "BOWL", "CUT", "WORM", "HOLE", "PUNCH", "BUG"],
    ["HORSE", "BACK", "BONE", "DRY", "DOCK", "BIRD", "CAGE"],
    ["BULL", "DOG", "HOUSE", "CAT", "NAP", "TIME", "FLY"],
    ["ANT", "HILL", "SIDE", "WALK", "WAY", "BIRD", "BATH"],
    ["DOG", "WATCH", "BIRD", "HOUSE", "CAT", "NAP", "TIME"],
    ["HORSE", "PLAY", "GROUND", "HOG", "WASH", "BEAR", "TRAP"],
    ["SPIDER", "WEB", "FOOT", "PRINT", "WOLF", "PACK", "ICE"],
    ["BULL", "RING", "WORM", "HOLE", "FISH", "POND", "LILY"],
    ["CAT", "FISH", "BOWL", "CUT", "WORM", "HOLE", "SAW"],
    // 8-word chains
    ["DOG", "HOUSE", "FLY", "FISH", "BOWL", "CUT", "WORM", "HOLE"],
    ["HORSE", "SHOE", "HORN", "BULL", "FROG", "MAN", "BEAR", "SKIN"],
    ["CAT", "WALK", "WAY", "SIDE", "KICK", "BACK", "BONE", "DRY"],
    ["DOG", "WATCH", "BIRD", "HOUSE", "CAT", "NAP", "TIME", "FLY"],
    ["HORSE", "PLAY", "GROUND", "HOG", "WASH", "BEAR", "TRAP", "DOOR"],
    ["SPIDER", "WEB", "FOOT", "PRINT", "WOLF", "PACK", "ICE", "BOX"],
    ["BULL", "RING", "WORM", "HOLE", "FISH", "POND", "LILY", "PAD"],
    ["CAT", "FISH", "BOWL", "CUT", "WORM", "HOLE", "SAW", "DUST"],
    ["FOX", "HUNT", "DOG", "BONE", "DRY", "DOCK", "BIRD", "CAGE"],
    ["BEAR", "TRAP", "DOOR", "BELL", "HOP", "SCOTCH", "TAPE", "WORM"],
    // 9-word chains
    ["DOG", "HOUSE", "FLY", "TRAP", "DOOR", "BELL", "HOP", "TOAD", "STOOL"],
    ["FISH", "BOWL", "CUT", "BACK", "BONE", "DRY", "DOCK", "BIRD", "CAGE"],
    ["DOG", "WATCH", "BIRD", "HOUSE", "CAT", "NAP", "TIME", "FLY", "TRAP"],
    ["HORSE", "PLAY", "GROUND", "HOG", "WASH", "BEAR", "TRAP", "DOOR", "BELL"],
    ["SPIDER", "WEB", "FOOT", "PRINT", "WOLF", "PACK", "ICE", "BOX", "CAR"],
    ["BULL", "RING", "WORM", "HOLE", "FISH", "POND", "LILY", "PAD", "LOCK"],
    ["CAT", "FISH", "BOWL", "CUT", "WORM", "HOLE", "SAW", "DUST", "BOWL"],
    ["FOX", "HUNT", "DOG", "BONE", "DRY", "DOCK", "BIRD", "CAGE", "MATCH"],
    ["BEAR", "TRAP", "DOOR", "BELL", "HOP", "SCOTCH", "TAPE", "WORM", "CAST"],
    ["WOLF", "PACK", "HORSE", "TAIL", "GATE", "WAY", "SIDE", "WALK", "WAY"],
    // 10-word chains
    ["DOG", "HOUSE", "CAT", "FISH", "BOWL", "CUT", "WORM", "HOLE", "PUNCH", "BUG"],
    ["HORSE", "BACK", "BONE", "DRY", "DOCK", "BIRD", "BATH", "ROOM", "MATE", "SHIP"],
    ["DOG", "WATCH", "BIRD", "HOUSE", "CAT", "NAP", "TIME", "FLY", "TRAP", "DOOR"],
    ["HORSE", "PLAY", "GROUND", "HOG", "WASH", "BEAR", "TRAP", "DOOR", "BELL", "HOP"],
    ["SPIDER", "WEB", "FOOT", "PRINT", "WOLF", "PACK", "ICE", "BOX", "CAR", "POOL"],
    ["BULL", "RING", "WORM", "HOLE", "FISH", "POND", "LILY", "PAD", "LOCK", "BOX"],
    ["CAT", "FISH", "BOWL", "CUT", "WORM", "HOLE", "SAW", "DUST", "BOWL", "GAME"],
    ["FOX", "HUNT", "DOG", "BONE", "DRY", "DOCK", "BIRD", "CAGE", "MATCH", "BOX"],
    ["BEAR", "TRAP", "DOOR", "BELL", "HOP", "SCOTCH", "TAPE", "WORM", "CAST", "IRON"],
    ["WOLF", "PACK", "HORSE", "TAIL", "GATE", "WAY", "SIDE", "WALK", "WAY", "POINT"],
  ],
  moviesAndShows: [
    ["STAR", "WARS", "GAME", "SHOW", "TIME"],
    ["DARK", "KNIGHT", "FALL", "GUY", "WIRE"],
    ["IRON", "MAN", "HUNT", "CLUB", "HOUSE"],
    ["DEAD", "POOL", "SIDE", "KICK", "START"],
    ["TOP", "GUN", "SHOT", "CLOCK", "WORK"],
    ["BREAK", "BAD", "LAND", "MARK", "FILM"],
    ["BLACK", "MIRROR", "IMAGE", "CAST", "IRON"],
    ["GOLD", "RUSH", "HOUR", "GLASS", "HOUSE"],
    ["FIGHT", "CLUB", "HOUSE", "FIRE", "WALL"],
    ["SPEED", "RACE", "TRACK", "STAR", "DUST"],
    ["STAR", "WARS", "GAME", "NIGHT", "CLUB", "HOUSE"],
    ["DARK", "KNIGHT", "FALL", "BACK", "STAGE", "DOOR"],
    ["IRON", "MAN", "HUNT", "GROUND", "WORK", "SHOP"],
    ["DEAD", "POOL", "SIDE", "LINE", "BACK", "FIRE"],
    ["BLACK", "MIRROR", "BALL", "GAME", "PLAN", "TREE"],
    ["TOP", "GUN", "SHOT", "CLOCK", "WORK", "SHOP"],
    ["BREAK", "BAD", "LAND", "MARK", "FILM", "REEL"],
    ["BLACK", "MIRROR", "IMAGE", "CAST", "IRON", "MAN"],
    ["FIGHT", "CLUB", "HOUSE", "FIRE", "WALL", "CLOCK"],
    ["SPEED", "RACE", "TRACK", "STAR", "DUST", "BOWL"],
    ["TOP", "GUN", "SHOT", "CLOCK", "TOWER", "BRIDGE", "WORK"],
    ["STAR", "DUST", "BOWL", "CUT", "BACK", "FIRE", "SIDE"],
    ["IRON", "MAN", "CAVE", "BEAR", "SKIN", "DEEP", "END"],
    ["STAR", "WARS", "GAME", "SHOW", "TIME", "LINE", "BACK"],
    ["DARK", "KNIGHT", "FALL", "GUY", "WIRE", "TAP", "SHOE"],
    ["IRON", "MAN", "HUNT", "CLUB", "HOUSE", "PARTY", "LINE"],
    ["DEAD", "POOL", "SIDE", "KICK", "START", "LINE", "BACK"],
    ["TOP", "GUN", "SHOT", "CLOCK", "WORK", "SHOP", "LIFT"],
    ["BREAK", "BAD", "LAND", "MARK", "FILM", "REEL", "LIFE"],
    ["BLACK", "MIRROR", "IMAGE", "CAST", "IRON", "MAN", "CAVE"],
    ["DEAD", "POOL", "HALL", "WAY", "SIDE", "LINE", "BACK", "STAGE"],
    ["STAR", "WARS", "GAME", "NIGHT", "FALL", "BACK", "BONE", "HEAD"],
    ["STAR", "WARS", "GAME", "SHOW", "TIME", "LINE", "BACK", "STAGE"],
    ["DARK", "KNIGHT", "FALL", "GUY", "WIRE", "TAP", "SHOE", "STRING"],
    ["IRON", "MAN", "HUNT", "CLUB", "HOUSE", "PARTY", "LINE", "BACK"],
    ["DEAD", "POOL", "SIDE", "KICK", "START", "LINE", "BACK", "FIRE"],
    ["TOP", "GUN", "SHOT", "CLOCK", "WORK", "SHOP", "LIFT", "OFF"],
    ["BREAK", "BAD", "LAND", "MARK", "FILM", "REEL", "LIFE", "TIME"],
    ["BLACK", "MIRROR", "IMAGE", "CAST", "IRON", "MAN", "CAVE", "IN"],
    ["FIGHT", "CLUB", "HOUSE", "FIRE", "WALL", "CLOCK", "TOWER", "BRIDGE"],
    ["STAR", "WARS", "GAME", "NIGHT", "FALL", "BACK", "BONE", "HEAD", "BAND"],
    ["STAR", "WARS", "GAME", "SHOW", "TIME", "LINE", "BACK", "STAGE", "DOOR"],
    ["DARK", "KNIGHT", "FALL", "GUY", "WIRE", "TAP", "SHOE", "STRING", "BEAN"],
    ["IRON", "MAN", "HUNT", "CLUB", "HOUSE", "PARTY", "LINE", "BACK", "BONE"],
    ["DEAD", "POOL", "SIDE", "KICK", "START", "LINE", "BACK", "FIRE", "WALL"],
    ["TOP", "GUN", "SHOT", "CLOCK", "WORK", "SHOP", "LIFT", "OFF", "SEASON"],
    ["BREAK", "BAD", "LAND", "MARK", "FILM", "REEL", "LIFE", "TIME", "LINE"],
    ["BLACK", "MIRROR", "IMAGE", "CAST", "IRON", "MAN", "CAVE", "IN", "DOOR"],
    ["FIGHT", "CLUB", "HOUSE", "FIRE", "WALL", "CLOCK", "TOWER", "BRIDGE", "WORK"],
    ["TOP", "GUN", "SHOT", "CLOCK", "TOWER", "BRIDGE", "WORK", "LOAD", "STAR", "LIGHT"],
    ["STAR", "WARS", "GAME", "SHOW", "TIME", "LINE", "BACK", "STAGE", "DOOR", "BELL"],
    ["DARK", "KNIGHT", "FALL", "GUY", "WIRE", "TAP", "SHOE", "STRING", "BEAN", "BAG"],
    ["IRON", "MAN", "HUNT", "CLUB", "HOUSE", "PARTY", "LINE", "BACK", "BONE", "DRY"],
    ["DEAD", "POOL", "SIDE", "KICK", "START", "LINE", "BACK", "FIRE", "WALL", "CLOCK"],
    ["TOP", "GUN", "SHOT", "CLOCK", "WORK", "SHOP", "LIFT", "OFF", "SEASON", "TICKET"],
    ["BREAK", "BAD", "LAND", "MARK", "FILM", "REEL", "LIFE", "TIME", "LINE", "BACK"],
    ["BLACK", "MIRROR", "IMAGE", "CAST", "IRON", "MAN", "CAVE", "IN", "DOOR", "BELL"],
    ["FIGHT", "CLUB", "HOUSE", "FIRE", "WALL", "CLOCK", "TOWER", "BRIDGE", "WORK", "SHOP"],
    ["SPEED", "RACE", "TRACK", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE", "HEAD"],
  ],
  disneyAndPixar: [
    ["ICE", "CASTLE", "ROCK", "STAR", "FISH"],
    ["TOY", "STORE", "ROOM", "MATE", "SHIP"],
    ["LION", "KING", "PIN", "POINT", "GUARD"],
    ["MAGIC", "CARPET", "RIDE", "SHARE", "CROP"],
    ["BEAST", "MODE", "LOCK", "SMITH", "FIRE"],
    ["GLASS", "SLIPPER", "SLIDE", "SHOW", "BOAT"],
    ["WISH", "BONE", "FIRE", "FLY", "WHEEL"],
    ["DREAM", "LAND", "MARK", "TIME", "LINE"],
    ["PIXIE", "DUST", "STORM", "CLOUD", "NINE"],
    ["FAIRY", "TALE", "SPIN", "WHEEL", "CHAIR"],
    ["ICE", "CASTLE", "ROCK", "BAND", "STAND", "STILL"],
    ["TOY", "STORE", "ROOM", "MATE", "SHIP", "WRECK"],
    ["LION", "KING", "PIN", "POINT", "GUARD", "RAIL"],
    ["MAGIC", "CARPET", "RIDE", "SHARE", "CROP", "TOP"],
    ["BEAST", "MODE", "LOCK", "SMITH", "FIRE", "TRUCK"],
    ["GLASS", "SLIPPER", "SLIDE", "SHOW", "BOAT", "HOUSE"],
    ["WISH", "BONE", "FIRE", "FLY", "WHEEL", "HOUSE"],
    ["DREAM", "LAND", "MARK", "TIME", "LINE", "BACK"],
    ["PIXIE", "DUST", "STORM", "CLOUD", "NINE", "LIVES"],
    ["FAIRY", "TALE", "SPIN", "WHEEL", "CHAIR", "LIFT"],
    ["MAGIC", "WAND", "STAR", "FISH", "BOWL", "CUT", "BACK"],
    ["TOY", "BOX", "CAR", "POOL", "SIDE", "KICK", "BACK"],
    ["ICE", "CASTLE", "ROCK", "STAR", "FISH", "BOWL", "CUT"],
    ["TOY", "STORE", "ROOM", "MATE", "SHIP", "WRECK", "AGE"],
    ["LION", "KING", "PIN", "POINT", "GUARD", "RAIL", "ROAD"],
    ["MAGIC", "CARPET", "RIDE", "SHARE", "CROP", "TOP", "HAT"],
    ["BEAST", "MODE", "LOCK", "SMITH", "FIRE", "TRUCK", "STOP"],
    ["GLASS", "SLIPPER", "SLIDE", "SHOW", "BOAT", "HOUSE", "PARTY"],
    ["WISH", "BONE", "FIRE", "FLY", "WHEEL", "HOUSE", "HOLD"],
    ["PIXIE", "DUST", "STORM", "CLOUD", "NINE", "LIVES", "MATTER"],
    ["DREAM", "LAND", "MARK", "DOWN", "HILL", "SIDE", "LINE", "BACK"],
    ["ICE", "CASTLE", "ROCK", "STAR", "FISH", "BOWL", "CUT", "BACK"],
    ["TOY", "STORE", "ROOM", "MATE", "SHIP", "WRECK", "AGE", "GROUP"],
    ["LION", "KING", "PIN", "POINT", "GUARD", "RAIL", "ROAD", "BLOCK"],
    ["MAGIC", "CARPET", "RIDE", "SHARE", "CROP", "TOP", "HAT", "TRICK"],
    ["BEAST", "MODE", "LOCK", "SMITH", "FIRE", "TRUCK", "STOP", "SIGN"],
    ["GLASS", "SLIPPER", "SLIDE", "SHOW", "BOAT", "HOUSE", "PARTY", "LINE"],
    ["WISH", "BONE", "FIRE", "FLY", "WHEEL", "HOUSE", "HOLD", "BACK"],
    ["PIXIE", "DUST", "STORM", "CLOUD", "NINE", "LIVES", "MATTER", "OF"],
    ["ICE", "CASTLE", "ROCK", "BAND", "STAND", "STILL", "LIFE", "TIME", "LINE"],
    ["TOY", "STORE", "ROOM", "MATE", "SHIP", "WRECK", "AGE", "GROUP", "CHAT"],
    ["LION", "KING", "PIN", "POINT", "GUARD", "RAIL", "ROAD", "BLOCK", "PARTY"],
    ["MAGIC", "CARPET", "RIDE", "SHARE", "CROP", "TOP", "HAT", "TRICK", "SHOT"],
    ["BEAST", "MODE", "LOCK", "SMITH", "FIRE", "TRUCK", "STOP", "SIGN", "LANGUAGE"],
    ["GLASS", "SLIPPER", "SLIDE", "SHOW", "BOAT", "HOUSE", "PARTY", "LINE", "BACK"],
    ["WISH", "BONE", "FIRE", "FLY", "WHEEL", "HOUSE", "HOLD", "BACK", "DOOR"],
    ["DREAM", "LAND", "MARK", "DOWN", "HILL", "SIDE", "LINE", "BACK", "BONE"],
    ["PIXIE", "DUST", "STORM", "CLOUD", "NINE", "LIVES", "MATTER", "OF", "TIME"],
    ["FAIRY", "TALE", "SPIN", "WHEEL", "CHAIR", "MAN", "HOLE", "PUNCH", "LINE", "BACK"],
    ["ICE", "CASTLE", "ROCK", "STAR", "FISH", "BOWL", "CUT", "BACK", "BONE", "DRY"],
    ["TOY", "STORE", "ROOM", "MATE", "SHIP", "WRECK", "AGE", "GROUP", "CHAT", "ROOM"],
    ["LION", "KING", "PIN", "POINT", "GUARD", "RAIL", "ROAD", "BLOCK", "PARTY", "LINE"],
    ["MAGIC", "CARPET", "RIDE", "SHARE", "CROP", "TOP", "HAT", "TRICK", "SHOT", "CLOCK"],
    ["BEAST", "MODE", "LOCK", "SMITH", "FIRE", "TRUCK", "STOP", "SIGN", "LANGUAGE", "ARTS"],
    ["GLASS", "SLIPPER", "SLIDE", "SHOW", "BOAT", "HOUSE", "PARTY", "LINE", "BACK", "STAGE"],
    ["WISH", "BONE", "FIRE", "FLY", "WHEEL", "HOUSE", "HOLD", "BACK", "DOOR", "BELL"],
    ["DREAM", "LAND", "MARK", "DOWN", "HILL", "SIDE", "LINE", "BACK", "BONE", "HEAD"],
  ],
  fpsGames: [
    ["HEAD", "SHOT", "GUN", "FIRE", "WALL"],
    ["CROSS", "HAIR", "TRIGGER", "POINT", "GUARD"],
    ["CAMP", "FIRE", "FIGHT", "CLUB", "HOUSE"],
    ["RUSH", "HOUR", "GLASS", "SCOPE", "SHOT"],
    ["SPAWN", "POINT", "BLANK", "SHOT", "GUN"],
    ["SNIPE", "HUNT", "GROUND", "ZERO", "HOUR"],
    ["FLASH", "BANG", "HEAD", "BAND", "WIDTH"],
    ["KILL", "SHOT", "CLOCK", "TOWER", "BLOCK"],
    ["QUICK", "SCOPE", "SHOT", "GUN", "FIRE"],
    ["FIRE", "FIGHT", "BACK", "STAB", "WOUND"],
    ["HEAD", "SHOT", "GUN", "FIRE", "WALL", "BANG"],
    ["CROSS", "HAIR", "PIN", "POINT", "GUARD", "RAIL"],
    ["HEAD", "SHOT", "GUN", "FIRE", "WALL", "CLOCK"],
    ["CROSS", "HAIR", "TRIGGER", "POINT", "GUARD", "DOG"],
    ["CAMP", "FIRE", "FIGHT", "CLUB", "HOUSE", "PARTY"],
    ["RUSH", "HOUR", "GLASS", "SCOPE", "SHOT", "CLOCK"],
    ["SPAWN", "POINT", "BLANK", "SHOT", "GUN", "METAL"],
    ["SNIPE", "HUNT", "GROUND", "ZERO", "HOUR", "HAND"],
    ["KILL", "SHOT", "CLOCK", "TOWER", "BLOCK", "PARTY"],
    ["QUICK", "SCOPE", "SHOT", "GUN", "FIRE", "DRILL"],
    ["CAMP", "FIRE", "FIGHT", "BACK", "STAB", "WOUND", "HEAL"],
    ["HEAD", "SHOT", "GUN", "FIRE", "WALL", "CLOCK", "TOWER"],
    ["CROSS", "HAIR", "TRIGGER", "POINT", "GUARD", "DOG", "HOUSE"],
    ["CAMP", "FIRE", "FIGHT", "CLUB", "HOUSE", "PARTY", "LINE"],
    ["RUSH", "HOUR", "GLASS", "SCOPE", "SHOT", "CLOCK", "TOWER"],
    ["SPAWN", "POINT", "BLANK", "SHOT", "GUN", "METAL", "HEAD"],
    ["SNIPE", "HUNT", "GROUND", "ZERO", "HOUR", "HAND", "BAG"],
    ["FLASH", "BANG", "HEAD", "BAND", "STAND", "STILL", "LIFE"],
    ["KILL", "SHOT", "CLOCK", "TOWER", "BLOCK", "PARTY", "LINE"],
    ["QUICK", "SCOPE", "SHOT", "GUN", "FIRE", "DRILL", "TEAM"],
    ["HEAD", "SHOT", "GUN", "FIRE", "SIDE", "WALK", "WAY", "POINT"],
    ["HEAD", "SHOT", "GUN", "FIRE", "WALL", "CLOCK", "TOWER", "BLOCK"],
    ["CROSS", "HAIR", "TRIGGER", "POINT", "GUARD", "DOG", "HOUSE", "PARTY"],
    ["CAMP", "FIRE", "FIGHT", "CLUB", "HOUSE", "PARTY", "LINE", "BACK"],
    ["RUSH", "HOUR", "GLASS", "SCOPE", "SHOT", "CLOCK", "TOWER", "BLOCK"],
    ["SPAWN", "POINT", "BLANK", "SHOT", "GUN", "METAL", "HEAD", "BAND"],
    ["SNIPE", "HUNT", "GROUND", "ZERO", "HOUR", "HAND", "BAG", "CHECK"],
    ["FLASH", "BANG", "HEAD", "BAND", "STAND", "STILL", "LIFE", "TIME"],
    ["KILL", "SHOT", "CLOCK", "TOWER", "BLOCK", "PARTY", "LINE", "BACK"],
    ["QUICK", "SCOPE", "SHOT", "GUN", "FIRE", "DRILL", "TEAM", "WORK"],
    ["CROSS", "HAIR", "PIN", "POINT", "GUARD", "RAIL", "ROAD", "BLOCK", "CHAIN"],
    ["HEAD", "SHOT", "GUN", "FIRE", "WALL", "CLOCK", "TOWER", "BLOCK", "PARTY"],
    ["CROSS", "HAIR", "TRIGGER", "POINT", "GUARD", "DOG", "HOUSE", "PARTY", "LINE"],
    ["CAMP", "FIRE", "FIGHT", "CLUB", "HOUSE", "PARTY", "LINE", "BACK", "STAGE"],
    ["RUSH", "HOUR", "GLASS", "SCOPE", "SHOT", "CLOCK", "TOWER", "BLOCK", "PARTY"],
    ["SPAWN", "POINT", "BLANK", "SHOT", "GUN", "METAL", "HEAD", "BAND", "STAND"],
    ["SNIPE", "HUNT", "GROUND", "ZERO", "HOUR", "HAND", "BAG", "CHECK", "POINT"],
    ["FLASH", "BANG", "HEAD", "BAND", "STAND", "STILL", "LIFE", "TIME", "LINE"],
    ["KILL", "SHOT", "CLOCK", "TOWER", "BLOCK", "PARTY", "LINE", "BACK", "BONE"],
    ["QUICK", "SCOPE", "SHOT", "GUN", "FIRE", "DRILL", "TEAM", "WORK", "BENCH"],
    ["HEAD", "SHOT", "GUN", "FIRE", "SIDE", "WALK", "WAY", "POINT", "GUARD", "RAIL"],
    ["HEAD", "SHOT", "GUN", "FIRE", "WALL", "CLOCK", "TOWER", "BLOCK", "PARTY", "LINE"],
    ["CROSS", "HAIR", "TRIGGER", "POINT", "GUARD", "DOG", "HOUSE", "PARTY", "LINE", "BACK"],
    ["CAMP", "FIRE", "FIGHT", "CLUB", "HOUSE", "PARTY", "LINE", "BACK", "STAGE", "DOOR"],
    ["RUSH", "HOUR", "GLASS", "SCOPE", "SHOT", "CLOCK", "TOWER", "BLOCK", "PARTY", "LINE"],
    ["SPAWN", "POINT", "BLANK", "SHOT", "GUN", "METAL", "HEAD", "BAND", "STAND", "STILL"],
    ["SNIPE", "HUNT", "GROUND", "ZERO", "HOUR", "HAND", "BAG", "CHECK", "POINT", "GUARD"],
    ["FLASH", "BANG", "HEAD", "BAND", "STAND", "STILL", "LIFE", "TIME", "LINE", "BACK"],
    ["KILL", "SHOT", "CLOCK", "TOWER", "BLOCK", "PARTY", "LINE", "BACK", "BONE", "HEAD"],
    ["QUICK", "SCOPE", "SHOT", "GUN", "FIRE", "DRILL", "TEAM", "WORK", "BENCH", "PRESS"],
  ],
  otherGames: [
    ["MINE", "CRAFT", "WORK", "BENCH", "PRESS"],
    ["BLOCK", "CHAIN", "MAIL", "BOX", "CAR"],
    ["WORLD", "BUILD", "UP", "GRADE", "SCHOOL"],
    ["QUEST", "LINE", "BACK", "PACK", "HORSE"],
    ["GAME", "PLAN", "TREE", "HOUSE", "HOLD"],
    ["GOLD", "MINE", "FIELD", "GOAL", "POST"],
    ["CRAFT", "WORK", "SHOP", "LIFT", "OFF"],
    ["POWER", "PLAY", "GROUND", "WORK", "FORCE"],
    ["LEVEL", "HEAD", "BAND", "STAND", "STILL"],
    ["BOSS", "FIGHT", "BACK", "BONE", "FIRE"],
    ["MINE", "CRAFT", "WORK", "BENCH", "PRESS", "PLAY"],
    ["BLOCK", "CHAIN", "LINK", "UP", "GRADE", "SCHOOL"],
    ["BLOCK", "CHAIN", "MAIL", "BOX", "CAR", "POOL"],
    ["WORLD", "BUILD", "UP", "GRADE", "SCHOOL", "HOUSE"],
    ["QUEST", "LINE", "BACK", "PACK", "HORSE", "SHOE"],
    ["GAME", "PLAN", "TREE", "HOUSE", "PARTY", "LINE"],
    ["GOLD", "MINE", "FIELD", "GOAL", "POST", "MARK"],
    ["CRAFT", "WORK", "SHOP", "LIFT", "OFF", "BASE"],
    ["POWER", "PLAY", "GROUND", "WORK", "FORCE", "FIELD"],
    ["LEVEL", "HEAD", "BAND", "STAND", "STILL", "LIFE"],
    ["GAME", "PLAN", "TREE", "HOUSE", "WIFE", "TIME", "LINE"],
    ["MINE", "CRAFT", "WORK", "BENCH", "PRESS", "PLAY", "TIME"],
    ["BLOCK", "CHAIN", "MAIL", "BOX", "CAR", "POOL", "SIDE"],
    ["WORLD", "BUILD", "UP", "GRADE", "SCHOOL", "HOUSE", "PARTY"],
    ["QUEST", "LINE", "BACK", "PACK", "HORSE", "SHOE", "HORN"],
    ["GAME", "PLAN", "TREE", "HOUSE", "PARTY", "LINE", "BACK"],
    ["GOLD", "MINE", "FIELD", "GOAL", "POST", "MARK", "DOWN"],
    ["CRAFT", "WORK", "SHOP", "LIFT", "OFF", "BASE", "LINE"],
    ["POWER", "PLAY", "GROUND", "WORK", "FORCE", "FIELD", "GOAL"],
    ["LEVEL", "HEAD", "BAND", "STAND", "STILL", "LIFE", "TIME"],
    ["MINE", "CRAFT", "WORK", "BENCH", "MARK", "DOWN", "HILL", "SIDE"],
    ["MINE", "CRAFT", "WORK", "BENCH", "PRESS", "PLAY", "TIME", "LINE"],
    ["BLOCK", "CHAIN", "MAIL", "BOX", "CAR", "POOL", "SIDE", "LINE"],
    ["WORLD", "BUILD", "UP", "GRADE", "SCHOOL", "HOUSE", "PARTY", "LINE"],
    ["QUEST", "LINE", "BACK", "PACK", "HORSE", "SHOE", "HORN", "BILL"],
    ["GAME", "PLAN", "TREE", "HOUSE", "PARTY", "LINE", "BACK", "STAGE"],
    ["GOLD", "MINE", "FIELD", "GOAL", "POST", "MARK", "DOWN", "HILL"],
    ["CRAFT", "WORK", "SHOP", "LIFT", "OFF", "BASE", "LINE", "BACK"],
    ["POWER", "PLAY", "GROUND", "WORK", "FORCE", "FIELD", "GOAL", "POST"],
    ["LEVEL", "HEAD", "BAND", "STAND", "STILL", "LIFE", "TIME", "LINE"],
    ["QUEST", "LINE", "BACK", "PACK", "HORSE", "SHOE", "HORN", "BILL", "BOARD"],
    ["MINE", "CRAFT", "WORK", "BENCH", "PRESS", "PLAY", "TIME", "LINE", "BACK"],
    ["BLOCK", "CHAIN", "MAIL", "BOX", "CAR", "POOL", "SIDE", "LINE", "BACK"],
    ["WORLD", "BUILD", "UP", "GRADE", "SCHOOL", "HOUSE", "PARTY", "LINE", "BACK"],
    ["QUEST", "LINE", "BACK", "PACK", "HORSE", "SHOE", "HORN", "BILL", "BOARD"],
    ["GAME", "PLAN", "TREE", "HOUSE", "PARTY", "LINE", "BACK", "STAGE", "DOOR"],
    ["GOLD", "MINE", "FIELD", "GOAL", "POST", "MARK", "DOWN", "HILL", "SIDE"],
    ["CRAFT", "WORK", "SHOP", "LIFT", "OFF", "BASE", "LINE", "BACK", "BONE"],
    ["POWER", "PLAY", "GROUND", "WORK", "FORCE", "FIELD", "GOAL", "POST", "MARK"],
    ["LEVEL", "HEAD", "BAND", "STAND", "STILL", "LIFE", "TIME", "LINE", "BACK"],
    ["GAME", "PLAN", "TREE", "HOUSE", "WIFE", "TIME", "LINE", "BACK", "BONE", "HEAD"],
    ["MINE", "CRAFT", "WORK", "BENCH", "PRESS", "PLAY", "TIME", "LINE", "BACK", "BONE"],
    ["BLOCK", "CHAIN", "MAIL", "BOX", "CAR", "POOL", "SIDE", "LINE", "BACK", "BONE"],
    ["WORLD", "BUILD", "UP", "GRADE", "SCHOOL", "HOUSE", "PARTY", "LINE", "BACK", "STAGE"],
    ["QUEST", "LINE", "BACK", "PACK", "HORSE", "SHOE", "HORN", "BILL", "BOARD", "GAME"],
    ["GAME", "PLAN", "TREE", "HOUSE", "PARTY", "LINE", "BACK", "STAGE", "DOOR", "BELL"],
    ["GOLD", "MINE", "FIELD", "GOAL", "POST", "MARK", "DOWN", "HILL", "SIDE", "KICK"],
    ["CRAFT", "WORK", "SHOP", "LIFT", "OFF", "BASE", "LINE", "BACK", "BONE", "DRY"],
    ["POWER", "PLAY", "GROUND", "WORK", "FORCE", "FIELD", "GOAL", "POST", "MARK", "DOWN"],
    ["LEVEL", "HEAD", "BAND", "STAND", "STILL", "LIFE", "TIME", "LINE", "BACK", "BONE"],
  ],
  food: [
    ["CHEESE", "CAKE", "WALK", "WAY", "SIDE"],
    ["HOT", "DOG", "HOUSE", "FIRE", "CRACKER"],
    ["BREAD", "BASKET", "CASE", "WORK", "BENCH"],
    ["EGG", "ROLL", "CALL", "BACK", "BONE"],
    ["CORN", "BREAD", "STICK", "BALL", "PARK"],
    ["MEAT", "BALL", "ROOM", "MATE", "SHIP"],
    ["PIE", "CRUST", "FALL", "BACK", "BONE"],
    ["PEPPER", "MINT", "CHIP", "SHOT", "GUN"],
    ["RICE", "BOWL", "CUT", "BACK", "FIRE"],
    ["CAKE", "POP", "CORN", "DOG", "BONE"],
    ["HOT", "DOG", "HOUSE", "FIRE", "CRACKER", "JACK"],
    ["BREAD", "BASKET", "CASE", "WORK", "BENCH", "PRESS"],
    ["CHEESE", "CAKE", "WALK", "WAY", "SIDE", "DISH"],
    ["EGG", "ROLL", "CALL", "BACK", "BONE", "DRY"],
    ["CORN", "BREAD", "STICK", "BALL", "PARK", "BENCH"],
    ["MEAT", "BALL", "ROOM", "MATE", "SHIP", "WRECK"],
    ["PIE", "CRUST", "FALL", "BACK", "BONE", "DRY"],
    ["PEPPER", "MINT", "CHIP", "SHOT", "GUN", "METAL"],
    ["RICE", "BOWL", "CUT", "BACK", "FIRE", "SIDE"],
    ["CAKE", "POP", "CORN", "DOG", "BONE", "DRY"],
    ["CHEESE", "CAKE", "WALK", "WAY", "SIDE", "KICK", "BACK"],
    ["HOT", "DOG", "HOUSE", "FIRE", "CRACKER", "JACK", "POT"],
    ["BREAD", "BASKET", "CASE", "WORK", "BENCH", "PRESS", "BOX"],
    ["EGG", "ROLL", "CALL", "BACK", "BONE", "DRY", "DOCK"],
    ["CORN", "BREAD", "STICK", "BALL", "PARK", "BENCH", "PRESS"],
    ["MEAT", "BALL", "ROOM", "MATE", "SHIP", "WRECK", "AGE"],
    ["PIE", "CRUST", "FALL", "BACK", "BONE", "DRY", "DOCK"],
    ["PEPPER", "MINT", "CHIP", "SHOT", "GUN", "METAL", "HEAD"],
    ["RICE", "BOWL", "CUT", "BACK", "FIRE", "SIDE", "WALK"],
    ["CAKE", "POP", "CORN", "DOG", "BONE", "DRY", "DOCK"],
    ["HOT", "DOG", "HOUSE", "FIRE", "SIDE", "WALK", "WAY", "POINT"],
    ["HOT", "DOG", "HOUSE", "FIRE", "CRACKER", "JACK", "POT", "ROAST"],
    ["BREAD", "BASKET", "CASE", "WORK", "BENCH", "PRESS", "BOX", "CAR"],
    ["EGG", "ROLL", "CALL", "BACK", "BONE", "DRY", "DOCK", "SIDE"],
    ["CORN", "BREAD", "STICK", "BALL", "PARK", "BENCH", "PRESS", "BOX"],
    ["MEAT", "BALL", "ROOM", "MATE", "SHIP", "WRECK", "AGE", "GROUP"],
    ["PIE", "CRUST", "FALL", "BACK", "BONE", "DRY", "DOCK", "BIRD"],
    ["PEPPER", "MINT", "CHIP", "SHOT", "GUN", "METAL", "HEAD", "BAND"],
    ["RICE", "BOWL", "CUT", "BACK", "FIRE", "SIDE", "WALK", "WAY"],
    ["CAKE", "POP", "CORN", "DOG", "BONE", "DRY", "DOCK", "BIRD"],
    ["BREAD", "BASKET", "BALL", "PARK", "LAND", "MARK", "DOWN", "HILL", "SIDE"],
    ["HOT", "DOG", "HOUSE", "FIRE", "CRACKER", "JACK", "POT", "ROAST", "BEEF"],
    ["BREAD", "BASKET", "CASE", "WORK", "BENCH", "PRESS", "BOX", "CAR", "POOL"],
    ["EGG", "ROLL", "CALL", "BACK", "BONE", "DRY", "DOCK", "SIDE", "LINE"],
    ["CORN", "BREAD", "STICK", "BALL", "PARK", "BENCH", "PRESS", "BOX", "CAR"],
    ["MEAT", "BALL", "ROOM", "MATE", "SHIP", "WRECK", "AGE", "GROUP", "CHAT"],
    ["PIE", "CRUST", "FALL", "BACK", "BONE", "DRY", "DOCK", "BIRD", "CAGE"],
    ["PEPPER", "MINT", "CHIP", "SHOT", "GUN", "METAL", "HEAD", "BAND", "STAND"],
    ["RICE", "BOWL", "CUT", "BACK", "FIRE", "SIDE", "WALK", "WAY", "POINT"],
    ["CAKE", "POP", "CORN", "DOG", "BONE", "DRY", "DOCK", "BIRD", "BATH"],
    ["CHEESE", "CAKE", "WALK", "WAY", "SIDE", "KICK", "BACK", "BONE", "HEAD", "BAND"],
    ["HOT", "DOG", "HOUSE", "FIRE", "CRACKER", "JACK", "POT", "ROAST", "BEEF", "STEW"],
    ["BREAD", "BASKET", "CASE", "WORK", "BENCH", "PRESS", "BOX", "CAR", "POOL", "SIDE"],
    ["EGG", "ROLL", "CALL", "BACK", "BONE", "DRY", "DOCK", "SIDE", "LINE", "BACK"],
    ["CORN", "BREAD", "STICK", "BALL", "PARK", "BENCH", "PRESS", "BOX", "CAR", "POOL"],
    ["MEAT", "BALL", "ROOM", "MATE", "SHIP", "WRECK", "AGE", "GROUP", "CHAT", "ROOM"],
    ["PIE", "CRUST", "FALL", "BACK", "BONE", "DRY", "DOCK", "BIRD", "CAGE", "MATCH"],
    ["PEPPER", "MINT", "CHIP", "SHOT", "GUN", "METAL", "HEAD", "BAND", "STAND", "STILL"],
    ["RICE", "BOWL", "CUT", "BACK", "FIRE", "SIDE", "WALK", "WAY", "POINT", "GUARD"],
    ["CAKE", "POP", "CORN", "DOG", "BONE", "DRY", "DOCK", "BIRD", "BATH", "ROOM"],
  ],
  drinks: [
    ["ICE", "TEA", "TIME", "LINE", "BACK"],
    ["ROOT", "BEER", "BELLY", "FLOP", "HOUSE"],
    ["MILK", "SHAKE", "DOWN", "HILL", "SIDE"],
    ["JUICE", "BOX", "CAR", "POOL", "SIDE"],
    ["SODA", "POP", "CORN", "FIELD", "GOAL"],
    ["WATER", "FALL", "BACK", "BONE", "DRY"],
    ["LEMON", "DROP", "KICK", "BACK", "FIRE"],
    ["CUP", "CAKE", "WALK", "WAY", "SIDE"],
    ["SHOT", "GLASS", "HOUSE", "BOAT", "LOAD"],
    ["BREW", "HOUSE", "HOLD", "BACK", "BONE"],
    ["ICE", "TEA", "TIME", "LINE", "BACK", "FIRE"],
    ["ROOT", "BEER", "BELLY", "FLOP", "HOUSE", "HOLD"],
    ["JUICE", "BOX", "CAR", "POOL", "SIDE", "LINE"],
    ["SODA", "POP", "CORN", "FIELD", "GOAL", "POST"],
    ["WATER", "FALL", "BACK", "BONE", "DRY", "DOCK"],
    ["LEMON", "DROP", "KICK", "BACK", "FIRE", "SIDE"],
    ["CUP", "CAKE", "WALK", "WAY", "SIDE", "DISH"],
    ["SHOT", "GLASS", "HOUSE", "BOAT", "LOAD", "LINE"],
    ["BREW", "HOUSE", "HOLD", "BACK", "BONE", "DRY"],
    ["COFFEE", "CUP", "CAKE", "WALK", "WAY", "SIDE"],
    ["MILK", "SHAKE", "DOWN", "HILL", "SIDE", "KICK", "BACK"],
    ["ICE", "TEA", "TIME", "LINE", "BACK", "FIRE", "SIDE"],
    ["ROOT", "BEER", "BELLY", "FLOP", "HOUSE", "HOLD", "BACK"],
    ["JUICE", "BOX", "CAR", "POOL", "SIDE", "LINE", "BACK"],
    ["SODA", "POP", "CORN", "FIELD", "GOAL", "POST", "MARK"],
    ["WATER", "FALL", "BACK", "BONE", "DRY", "DOCK", "BIRD"],
    ["LEMON", "DROP", "KICK", "BACK", "FIRE", "SIDE", "WALK"],
    ["CUP", "CAKE", "WALK", "WAY", "SIDE", "DISH", "RAG"],
    ["SHOT", "GLASS", "HOUSE", "BOAT", "LOAD", "LINE", "BACK"],
    ["BREW", "HOUSE", "HOLD", "BACK", "BONE", "DRY", "DOCK"],
    ["ICE", "TEA", "TIME", "LINE", "BACK", "FIRE", "SIDE", "WALK"],
    ["ROOT", "BEER", "BELLY", "FLOP", "HOUSE", "HOLD", "BACK", "DOOR"],
    ["JUICE", "BOX", "CAR", "POOL", "SIDE", "LINE", "BACK", "BONE"],
    ["SODA", "POP", "CORN", "FIELD", "GOAL", "POST", "MARK", "DOWN"],
    ["WATER", "FALL", "BACK", "BONE", "DRY", "DOCK", "BIRD", "CAGE"],
    ["LEMON", "DROP", "KICK", "BACK", "FIRE", "SIDE", "WALK", "WAY"],
    ["CUP", "CAKE", "WALK", "WAY", "SIDE", "DISH", "RAG", "DOLL"],
    ["SHOT", "GLASS", "HOUSE", "BOAT", "LOAD", "LINE", "BACK", "STAGE"],
    ["BREW", "HOUSE", "HOLD", "BACK", "BONE", "DRY", "DOCK", "SIDE"],
    ["COFFEE", "CUP", "CAKE", "WALK", "WAY", "SIDE", "LINE", "BACK"],
    ["ROOT", "BEER", "BELLY", "FLOP", "HOUSE", "HOLD", "BACK", "BONE", "DRY"],
    ["ICE", "TEA", "TIME", "LINE", "BACK", "FIRE", "SIDE", "WALK", "WAY"],
    ["JUICE", "BOX", "CAR", "POOL", "SIDE", "LINE", "BACK", "BONE", "HEAD"],
    ["SODA", "POP", "CORN", "FIELD", "GOAL", "POST", "MARK", "DOWN", "HILL"],
    ["WATER", "FALL", "BACK", "BONE", "DRY", "DOCK", "BIRD", "CAGE", "MATCH"],
    ["LEMON", "DROP", "KICK", "BACK", "FIRE", "SIDE", "WALK", "WAY", "POINT"],
    ["CUP", "CAKE", "WALK", "WAY", "SIDE", "DISH", "RAG", "DOLL", "HOUSE"],
    ["SHOT", "GLASS", "HOUSE", "BOAT", "LOAD", "LINE", "BACK", "STAGE", "DOOR"],
    ["BREW", "HOUSE", "HOLD", "BACK", "BONE", "DRY", "DOCK", "SIDE", "LINE"],
    ["COFFEE", "CUP", "CAKE", "WALK", "WAY", "SIDE", "LINE", "BACK", "BONE"],
    ["MILK", "SHAKE", "DOWN", "HILL", "SIDE", "KICK", "BACK", "BONE", "HEAD", "BAND"],
    ["ICE", "TEA", "TIME", "LINE", "BACK", "FIRE", "SIDE", "WALK", "WAY", "POINT"],
    ["ROOT", "BEER", "BELLY", "FLOP", "HOUSE", "HOLD", "BACK", "BONE", "HEAD", "BAND"],
    ["JUICE", "BOX", "CAR", "POOL", "SIDE", "LINE", "BACK", "BONE", "HEAD", "BAND"],
    ["SODA", "POP", "CORN", "FIELD", "GOAL", "POST", "MARK", "DOWN", "HILL", "SIDE"],
    ["WATER", "FALL", "BACK", "BONE", "DRY", "DOCK", "BIRD", "CAGE", "MATCH", "BOX"],
    ["LEMON", "DROP", "KICK", "BACK", "FIRE", "SIDE", "WALK", "WAY", "POINT", "GUARD"],
    ["CUP", "CAKE", "WALK", "WAY", "SIDE", "DISH", "RAG", "DOLL", "HOUSE", "PARTY"],
    ["SHOT", "GLASS", "HOUSE", "BOAT", "LOAD", "LINE", "BACK", "STAGE", "DOOR", "BELL"],
    ["BREW", "HOUSE", "HOLD", "BACK", "BONE", "DRY", "DOCK", "SIDE", "LINE", "BACK"],
  ],
  restaurants: [
    ["FAST", "FOOD", "COURT", "SIDE", "WALK"],
    ["DRIVE", "THROUGH", "BACK", "DOOR", "BELL"],
    ["TAKE", "OUT", "SIDE", "LINE", "BACK"],
    ["COOK", "BOOK", "MARK", "DOWN", "TOWN"],
    ["TABLE", "TOP", "SIDE", "KICK", "BACK"],
    ["DINE", "OUT", "BREAK", "FAST", "FOOD"],
    ["GRILL", "MARK", "DOWN", "TOWN", "HOUSE"],
    ["MENU", "BOARD", "WALK", "WAY", "SIDE"],
    ["FORK", "LIFT", "OFF", "ROAD", "BLOCK"],
    ["PLATE", "GLASS", "HOUSE", "HOLD", "BACK"],
    ["FAST", "FOOD", "COURT", "SIDE", "WALK", "WAY"],
    ["DRIVE", "THROUGH", "BACK", "DOOR", "BELL", "HOP"],
    ["TAKE", "OUT", "SIDE", "LINE", "BACK", "DOOR"],
    ["COOK", "BOOK", "MARK", "DOWN", "TOWN", "HOUSE"],
    ["TABLE", "TOP", "SIDE", "KICK", "BACK", "BONE"],
    ["DINE", "OUT", "BREAK", "FAST", "FOOD", "COURT"],
    ["GRILL", "MARK", "DOWN", "TOWN", "HOUSE", "PARTY"],
    ["MENU", "BOARD", "WALK", "WAY", "SIDE", "DISH"],
    ["FORK", "LIFT", "OFF", "ROAD", "BLOCK", "PARTY"],
    ["PLATE", "GLASS", "HOUSE", "HOLD", "BACK", "DOOR"],
    ["COOK", "BOOK", "MARK", "DOWN", "TOWN", "HOUSE", "HOLD"],
    ["FAST", "FOOD", "COURT", "SIDE", "WALK", "WAY", "POINT"],
    ["DRIVE", "THROUGH", "BACK", "DOOR", "BELL", "HOP", "SCOTCH"],
    ["TAKE", "OUT", "SIDE", "LINE", "BACK", "DOOR", "BELL"],
    ["TABLE", "TOP", "SIDE", "KICK", "BACK", "BONE", "HEAD"],
    ["DINE", "OUT", "BREAK", "FAST", "FOOD", "COURT", "SIDE"],
    ["GRILL", "MARK", "DOWN", "TOWN", "HOUSE", "PARTY", "LINE"],
    ["MENU", "BOARD", "WALK", "WAY", "SIDE", "DISH", "RAG"],
    ["FORK", "LIFT", "OFF", "ROAD", "BLOCK", "PARTY", "LINE"],
    ["PLATE", "GLASS", "HOUSE", "HOLD", "BACK", "DOOR", "BELL"],
    ["FAST", "FOOD", "COURT", "SIDE", "WALK", "WAY", "POINT", "GUARD"],
    ["DRIVE", "THROUGH", "BACK", "DOOR", "BELL", "HOP", "SCOTCH", "TAPE"],
    ["TAKE", "OUT", "SIDE", "LINE", "BACK", "DOOR", "BELL", "HOP"],
    ["COOK", "BOOK", "MARK", "DOWN", "TOWN", "HOUSE", "HOLD", "BACK"],
    ["TABLE", "TOP", "SIDE", "KICK", "BACK", "BONE", "HEAD", "BAND"],
    ["DINE", "OUT", "BREAK", "FAST", "FOOD", "COURT", "SIDE", "LINE"],
    ["GRILL", "MARK", "DOWN", "TOWN", "HOUSE", "PARTY", "LINE", "BACK"],
    ["MENU", "BOARD", "WALK", "WAY", "SIDE", "DISH", "RAG", "DOLL"],
    ["FORK", "LIFT", "OFF", "ROAD", "BLOCK", "PARTY", "LINE", "BACK"],
    ["PLATE", "GLASS", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP"],
    ["TABLE", "TOP", "SIDE", "KICK", "BACK", "BONE", "HEAD", "BAND", "STAND"],
    ["FAST", "FOOD", "COURT", "SIDE", "WALK", "WAY", "POINT", "GUARD", "RAIL"],
    ["DRIVE", "THROUGH", "BACK", "DOOR", "BELL", "HOP", "SCOTCH", "TAPE", "WORM"],
    ["TAKE", "OUT", "SIDE", "LINE", "BACK", "DOOR", "BELL", "HOP", "SCOTCH"],
    ["COOK", "BOOK", "MARK", "DOWN", "TOWN", "HOUSE", "HOLD", "BACK", "DOOR"],
    ["DINE", "OUT", "BREAK", "FAST", "FOOD", "COURT", "SIDE", "LINE", "BACK"],
    ["GRILL", "MARK", "DOWN", "TOWN", "HOUSE", "PARTY", "LINE", "BACK", "STAGE"],
    ["MENU", "BOARD", "WALK", "WAY", "SIDE", "DISH", "RAG", "DOLL", "HOUSE"],
    ["FORK", "LIFT", "OFF", "ROAD", "BLOCK", "PARTY", "LINE", "BACK", "BONE"],
    ["PLATE", "GLASS", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP", "SCOTCH"],
    ["DINE", "OUT", "BREAK", "FAST", "FOOD", "COURT", "SIDE", "LINE", "BACK", "BONE"],
    ["FAST", "FOOD", "COURT", "SIDE", "WALK", "WAY", "POINT", "GUARD", "RAIL", "ROAD"],
    ["DRIVE", "THROUGH", "BACK", "DOOR", "BELL", "HOP", "SCOTCH", "TAPE", "WORM", "CAST"],
    ["TAKE", "OUT", "SIDE", "LINE", "BACK", "DOOR", "BELL", "HOP", "SCOTCH", "TAPE"],
    ["COOK", "BOOK", "MARK", "DOWN", "TOWN", "HOUSE", "HOLD", "BACK", "DOOR", "BELL"],
    ["TABLE", "TOP", "SIDE", "KICK", "BACK", "BONE", "HEAD", "BAND", "STAND", "STILL"],
    ["GRILL", "MARK", "DOWN", "TOWN", "HOUSE", "PARTY", "LINE", "BACK", "STAGE", "DOOR"],
    ["MENU", "BOARD", "WALK", "WAY", "SIDE", "DISH", "RAG", "DOLL", "HOUSE", "PARTY"],
    ["FORK", "LIFT", "OFF", "ROAD", "BLOCK", "PARTY", "LINE", "BACK", "BONE", "HEAD"],
    ["PLATE", "GLASS", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP", "SCOTCH", "TAPE"],
  ],
  carBrands: [
    ["ROAD", "SIDE", "KICK", "START", "LINE"],
    ["SPEED", "BUMP", "STOCK", "CAR", "POOL"],
    ["GEAR", "SHIFT", "WORK", "BENCH", "PRESS"],
    ["WHEEL", "SPIN", "OFF", "ROAD", "BLOCK"],
    ["BRAKE", "LIGHT", "HOUSE", "HOLD", "BACK"],
    ["DRIVE", "WAY", "SIDE", "LINE", "BACK"],
    ["RACE", "TRACK", "STAR", "DUST", "PAN"],
    ["TURN", "PIKE", "FISH", "HOOK", "LINE"],
    ["PARK", "BENCH", "PRESS", "BOX", "CAR"],
    ["GAS", "LIGHT", "HOUSE", "FIRE", "TRUCK"],
    ["ROAD", "SIDE", "KICK", "START", "LINE", "BACK"],
    ["SPEED", "BUMP", "STOCK", "CAR", "POOL", "SIDE"],
    ["WHEEL", "SPIN", "OFF", "ROAD", "BLOCK", "PARTY"],
    ["BRAKE", "LIGHT", "HOUSE", "HOLD", "BACK", "DOOR"],
    ["DRIVE", "WAY", "SIDE", "LINE", "BACK", "DOOR"],
    ["RACE", "TRACK", "STAR", "DUST", "PAN", "CAKE"],
    ["TURN", "PIKE", "FISH", "HOOK", "LINE", "BACK"],
    ["PARK", "BENCH", "PRESS", "BOX", "CAR", "POOL"],
    ["GAS", "LIGHT", "HOUSE", "FIRE", "TRUCK", "STOP"],
    ["ENGINE", "BLOCK", "PARTY", "LINE", "BACK", "UP"],
    ["GEAR", "SHIFT", "WORK", "BENCH", "MARK", "DOWN", "HILL"],
    ["ROAD", "SIDE", "KICK", "START", "LINE", "BACK", "DOOR"],
    ["SPEED", "BUMP", "STOCK", "CAR", "POOL", "SIDE", "LINE"],
    ["WHEEL", "SPIN", "OFF", "ROAD", "BLOCK", "PARTY", "LINE"],
    ["BRAKE", "LIGHT", "HOUSE", "HOLD", "BACK", "DOOR", "BELL"],
    ["DRIVE", "WAY", "SIDE", "LINE", "BACK", "DOOR", "BELL"],
    ["RACE", "TRACK", "STAR", "DUST", "PAN", "CAKE", "WALK"],
    ["TURN", "PIKE", "FISH", "HOOK", "LINE", "BACK", "BONE"],
    ["PARK", "BENCH", "PRESS", "BOX", "CAR", "POOL", "SIDE"],
    ["GAS", "LIGHT", "HOUSE", "FIRE", "TRUCK", "STOP", "SIGN"],
    ["WHEEL", "SPIN", "OFF", "ROAD", "BLOCK", "CHAIN", "MAIL", "BOX"],
    ["ROAD", "SIDE", "KICK", "START", "LINE", "BACK", "DOOR", "BELL"],
    ["SPEED", "BUMP", "STOCK", "CAR", "POOL", "SIDE", "LINE", "BACK"],
    ["BRAKE", "LIGHT", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP"],
    ["DRIVE", "WAY", "SIDE", "LINE", "BACK", "DOOR", "BELL", "HOP"],
    ["RACE", "TRACK", "STAR", "DUST", "PAN", "CAKE", "WALK", "WAY"],
    ["TURN", "PIKE", "FISH", "HOOK", "LINE", "BACK", "BONE", "DRY"],
    ["PARK", "BENCH", "PRESS", "BOX", "CAR", "POOL", "SIDE", "LINE"],
    ["GAS", "LIGHT", "HOUSE", "FIRE", "TRUCK", "STOP", "SIGN", "LANGUAGE"],
    ["ENGINE", "BLOCK", "PARTY", "LINE", "BACK", "UP", "TIME", "LINE"],
    ["DRIVE", "WAY", "POINT", "GUARD", "RAIL", "ROAD", "SIDE", "KICK", "BACK"],
    ["ROAD", "SIDE", "KICK", "START", "LINE", "BACK", "DOOR", "BELL", "HOP"],
    ["SPEED", "BUMP", "STOCK", "CAR", "POOL", "SIDE", "LINE", "BACK", "BONE"],
    ["WHEEL", "SPIN", "OFF", "ROAD", "BLOCK", "CHAIN", "MAIL", "BOX", "CAR"],
    ["BRAKE", "LIGHT", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP", "SCOTCH"],
    ["RACE", "TRACK", "STAR", "DUST", "PAN", "CAKE", "WALK", "WAY", "SIDE"],
    ["TURN", "PIKE", "FISH", "HOOK", "LINE", "BACK", "BONE", "DRY", "DOCK"],
    ["PARK", "BENCH", "PRESS", "BOX", "CAR", "POOL", "SIDE", "LINE", "BACK"],
    ["GAS", "LIGHT", "HOUSE", "FIRE", "TRUCK", "STOP", "SIGN", "LANGUAGE", "ARTS"],
    ["ENGINE", "BLOCK", "PARTY", "LINE", "BACK", "UP", "TIME", "LINE", "BACK"],
    ["RACE", "TRACK", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE", "HEAD", "BAND"],
    ["ROAD", "SIDE", "KICK", "START", "LINE", "BACK", "DOOR", "BELL", "HOP", "SCOTCH"],
    ["SPEED", "BUMP", "STOCK", "CAR", "POOL", "SIDE", "LINE", "BACK", "BONE", "HEAD"],
    ["WHEEL", "SPIN", "OFF", "ROAD", "BLOCK", "CHAIN", "MAIL", "BOX", "CAR", "POOL"],
    ["BRAKE", "LIGHT", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP", "SCOTCH", "TAPE"],
    ["DRIVE", "WAY", "POINT", "GUARD", "RAIL", "ROAD", "SIDE", "KICK", "BACK", "BONE"],
    ["TURN", "PIKE", "FISH", "HOOK", "LINE", "BACK", "BONE", "DRY", "DOCK", "BIRD"],
    ["PARK", "BENCH", "PRESS", "BOX", "CAR", "POOL", "SIDE", "LINE", "BACK", "BONE"],
    ["GAS", "LIGHT", "HOUSE", "FIRE", "TRUCK", "STOP", "SIGN", "LANGUAGE", "ARTS", "CLASS"],
    ["ENGINE", "BLOCK", "PARTY", "LINE", "BACK", "UP", "TIME", "LINE", "BACK", "BONE"],
  ],
  luxuryBrands: [
    ["GOLD", "CHAIN", "LINK", "UP", "SCALE"],
    ["SILK", "ROAD", "BLOCK", "CHAIN", "MAIL"],
    ["PEARL", "RING", "SIDE", "LINE", "BACK"],
    ["CROWN", "JEWEL", "BOX", "CAR", "POOL"],
    ["STONE", "COLD", "FRONT", "LINE", "BACK"],
    ["STYLE", "SHEET", "ROCK", "STAR", "DUST"],
    ["WATCH", "TOWER", "BRIDGE", "WORK", "SHOP"],
    ["BRAND", "NAME", "TAG", "TEAM", "WORK"],
    ["CLASS", "ROOM", "MATE", "SHIP", "WRECK"],
    ["FINE", "PRINT", "SHOP", "LIFT", "OFF"],
    ["GOLD", "CHAIN", "LINK", "UP", "GRADE", "SCHOOL"],
    ["SILK", "ROAD", "BLOCK", "CHAIN", "MAIL", "BOX"],
    ["PEARL", "RING", "SIDE", "LINE", "BACK", "DOOR"],
    ["CROWN", "JEWEL", "BOX", "CAR", "POOL", "SIDE"],
    ["STONE", "COLD", "FRONT", "LINE", "BACK", "DOOR"],
    ["STYLE", "SHEET", "ROCK", "STAR", "DUST", "BOWL"],
    ["WATCH", "TOWER", "BRIDGE", "WORK", "SHOP", "LIFT"],
    ["BRAND", "NAME", "TAG", "TEAM", "WORK", "SHOP"],
    ["CLASS", "ROOM", "MATE", "SHIP", "WRECK", "AGE"],
    ["FINE", "PRINT", "SHOP", "LIFT", "OFF", "SEASON"],
    ["CROWN", "JEWEL", "BOX", "CAR", "POOL", "SIDE", "KICK"],
    ["GOLD", "CHAIN", "LINK", "UP", "GRADE", "SCHOOL", "HOUSE"],
    ["SILK", "ROAD", "BLOCK", "CHAIN", "MAIL", "BOX", "CAR"],
    ["PEARL", "RING", "SIDE", "LINE", "BACK", "DOOR", "BELL"],
    ["STONE", "COLD", "FRONT", "LINE", "BACK", "DOOR", "BELL"],
    ["STYLE", "SHEET", "ROCK", "STAR", "DUST", "BOWL", "CUT"],
    ["WATCH", "TOWER", "BRIDGE", "WORK", "SHOP", "LIFT", "OFF"],
    ["BRAND", "NAME", "TAG", "TEAM", "WORK", "SHOP", "LIFT"],
    ["CLASS", "ROOM", "MATE", "SHIP", "WRECK", "AGE", "GROUP"],
    ["FINE", "PRINT", "SHOP", "LIFT", "OFF", "SEASON", "TICKET"],
    ["GOLD", "CHAIN", "LINK", "UP", "GRADE", "SCHOOL", "HOUSE", "HOLD"],
    ["SILK", "ROAD", "BLOCK", "CHAIN", "MAIL", "BOX", "CAR", "POOL"],
    ["PEARL", "RING", "SIDE", "LINE", "BACK", "DOOR", "BELL", "HOP"],
    ["CROWN", "JEWEL", "BOX", "CAR", "POOL", "SIDE", "KICK", "BACK"],
    ["STONE", "COLD", "FRONT", "LINE", "BACK", "DOOR", "BELL", "HOP"],
    ["STYLE", "SHEET", "ROCK", "STAR", "DUST", "BOWL", "CUT", "BACK"],
    ["WATCH", "TOWER", "BRIDGE", "WORK", "SHOP", "LIFT", "OFF", "SEASON"],
    ["BRAND", "NAME", "TAG", "TEAM", "WORK", "SHOP", "LIFT", "OFF"],
    ["CLASS", "ROOM", "MATE", "SHIP", "WRECK", "AGE", "GROUP", "CHAT"],
    ["FINE", "PRINT", "SHOP", "LIFT", "OFF", "SEASON", "TICKET", "STUB"],
    ["SILK", "ROAD", "BLOCK", "CHAIN", "MAIL", "BOX", "CAR", "POOL", "SIDE"],
    ["GOLD", "CHAIN", "LINK", "UP", "GRADE", "SCHOOL", "HOUSE", "HOLD", "BACK"],
    ["PEARL", "RING", "SIDE", "LINE", "BACK", "DOOR", "BELL", "HOP", "SCOTCH"],
    ["CROWN", "JEWEL", "BOX", "CAR", "POOL", "SIDE", "KICK", "BACK", "BONE"],
    ["STONE", "COLD", "FRONT", "LINE", "BACK", "DOOR", "BELL", "HOP", "SCOTCH"],
    ["STYLE", "SHEET", "ROCK", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE"],
    ["WATCH", "TOWER", "BRIDGE", "WORK", "SHOP", "LIFT", "OFF", "SEASON", "TICKET"],
    ["BRAND", "NAME", "TAG", "TEAM", "WORK", "SHOP", "LIFT", "OFF", "SEASON"],
    ["CLASS", "ROOM", "MATE", "SHIP", "WRECK", "AGE", "GROUP", "CHAT", "ROOM"],
    ["FINE", "PRINT", "SHOP", "LIFT", "OFF", "SEASON", "TICKET", "STUB", "BOOK"],
    ["WATCH", "TOWER", "BRIDGE", "WORK", "BENCH", "MARK", "DOWN", "HILL", "SIDE", "LINE"],
    ["GOLD", "CHAIN", "LINK", "UP", "GRADE", "SCHOOL", "HOUSE", "HOLD", "BACK", "DOOR"],
    ["SILK", "ROAD", "BLOCK", "CHAIN", "MAIL", "BOX", "CAR", "POOL", "SIDE", "LINE"],
    ["PEARL", "RING", "SIDE", "LINE", "BACK", "DOOR", "BELL", "HOP", "SCOTCH", "TAPE"],
    ["CROWN", "JEWEL", "BOX", "CAR", "POOL", "SIDE", "KICK", "BACK", "BONE", "HEAD"],
    ["STONE", "COLD", "FRONT", "LINE", "BACK", "DOOR", "BELL", "HOP", "SCOTCH", "TAPE"],
    ["STYLE", "SHEET", "ROCK", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE", "DRY"],
    ["BRAND", "NAME", "TAG", "TEAM", "WORK", "SHOP", "LIFT", "OFF", "SEASON", "TICKET"],
    ["CLASS", "ROOM", "MATE", "SHIP", "WRECK", "AGE", "GROUP", "CHAT", "ROOM", "MATE"],
    ["FINE", "PRINT", "SHOP", "LIFT", "OFF", "SEASON", "TICKET", "STUB", "BOOK", "CASE"],
  ],
  sports: [
    ["BALL", "GAME", "PLAN", "TREE", "HOUSE"],
    ["GOAL", "POST", "MARK", "DOWN", "HILL"],
    ["COURT", "SIDE", "LINE", "BACK", "BONE"],
    ["NET", "WORK", "BENCH", "PRESS", "BOX"],
    ["HOME", "RUN", "BACK", "FLIP", "SIDE"],
    ["KICK", "BACK", "BOARD", "GAME", "PLAN"],
    ["FIELD", "GOAL", "POST", "MARK", "DOWN"],
    ["PLAY", "GROUND", "WORK", "FORCE", "FEED"],
    ["RING", "SIDE", "KICK", "BACK", "BONE"],
    ["TRACK", "STAR", "DUST", "BOWL", "CUT"],
    ["BALL", "GAME", "PLAN", "TREE", "HOUSE", "HOLD"],
    ["GOAL", "POST", "MARK", "DOWN", "HILL", "SIDE"],
    ["COURT", "SIDE", "LINE", "BACK", "BONE", "HEAD"],
    ["NET", "WORK", "BENCH", "PRESS", "BOX", "CAR"],
    ["HOME", "RUN", "BACK", "FLIP", "SIDE", "LINE"],
    ["KICK", "BACK", "BOARD", "GAME", "PLAN", "TREE"],
    ["FIELD", "GOAL", "POST", "MARK", "DOWN", "HILL"],
    ["PLAY", "GROUND", "WORK", "FORCE", "FEED", "BACK"],
    ["RING", "SIDE", "KICK", "BACK", "BONE", "DRY"],
    ["TRACK", "STAR", "DUST", "BOWL", "CUT", "BACK"],
    ["COURT", "SIDE", "LINE", "BACK", "BONE", "HEAD", "BAND"],
    ["BALL", "GAME", "PLAN", "TREE", "HOUSE", "HOLD", "BACK"],
    ["GOAL", "POST", "MARK", "DOWN", "HILL", "SIDE", "KICK"],
    ["NET", "WORK", "BENCH", "PRESS", "BOX", "CAR", "POOL"],
    ["HOME", "RUN", "BACK", "FLIP", "SIDE", "LINE", "BACK"],
    ["KICK", "BACK", "BOARD", "GAME", "PLAN", "TREE", "HOUSE"],
    ["FIELD", "GOAL", "POST", "MARK", "DOWN", "HILL", "SIDE"],
    ["PLAY", "GROUND", "WORK", "FORCE", "FEED", "BACK", "BONE"],
    ["RING", "SIDE", "KICK", "BACK", "BONE", "DRY", "DOCK"],
    ["TRACK", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE"],
    ["BALL", "GAME", "PLAN", "TREE", "HOUSE", "HOLD", "BACK", "BONE"],
    ["GOAL", "POST", "MARK", "DOWN", "HILL", "SIDE", "KICK", "BACK"],
    ["COURT", "SIDE", "LINE", "BACK", "BONE", "HEAD", "BAND", "STAND"],
    ["NET", "WORK", "BENCH", "PRESS", "BOX", "CAR", "POOL", "SIDE"],
    ["HOME", "RUN", "BACK", "FLIP", "SIDE", "LINE", "BACK", "BONE"],
    ["KICK", "BACK", "BOARD", "GAME", "PLAN", "TREE", "HOUSE", "HOLD"],
    ["FIELD", "GOAL", "POST", "MARK", "DOWN", "HILL", "SIDE", "KICK"],
    ["PLAY", "GROUND", "WORK", "FORCE", "FEED", "BACK", "BONE", "DRY"],
    ["TRACK", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE", "HEAD"],
    ["GOAL", "POST", "MARK", "DOWN", "HILL", "SIDE", "KICK", "BACK", "DOOR"],
    ["BALL", "GAME", "PLAN", "TREE", "HOUSE", "HOLD", "BACK", "BONE", "HEAD"],
    ["COURT", "SIDE", "LINE", "BACK", "BONE", "HEAD", "BAND", "STAND", "STILL"],
    ["NET", "WORK", "BENCH", "PRESS", "BOX", "CAR", "POOL", "SIDE", "LINE"],
    ["HOME", "RUN", "BACK", "FLIP", "SIDE", "LINE", "BACK", "BONE", "HEAD"],
    ["KICK", "BACK", "BOARD", "GAME", "PLAN", "TREE", "HOUSE", "HOLD", "BACK"],
    ["FIELD", "GOAL", "POST", "MARK", "DOWN", "HILL", "SIDE", "KICK", "BACK"],
    ["PLAY", "GROUND", "WORK", "FORCE", "FEED", "BACK", "BONE", "DRY", "DOCK"],
    ["RING", "SIDE", "KICK", "BACK", "BONE", "DRY", "DOCK", "BIRD", "CAGE"],
    ["TRACK", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE", "HEAD", "BAND"],
    ["HOME", "RUN", "BACK", "BONE", "HEAD", "BAND", "STAND", "STILL", "LIFE", "TIME"],
    ["BALL", "GAME", "PLAN", "TREE", "HOUSE", "HOLD", "BACK", "BONE", "HEAD", "BAND"],
    ["GOAL", "POST", "MARK", "DOWN", "HILL", "SIDE", "KICK", "BACK", "DOOR", "BELL"],
    ["COURT", "SIDE", "LINE", "BACK", "BONE", "HEAD", "BAND", "STAND", "STILL", "LIFE"],
    ["NET", "WORK", "BENCH", "PRESS", "BOX", "CAR", "POOL", "SIDE", "LINE", "BACK"],
    ["KICK", "BACK", "BOARD", "GAME", "PLAN", "TREE", "HOUSE", "HOLD", "BACK", "DOOR"],
    ["FIELD", "GOAL", "POST", "MARK", "DOWN", "HILL", "SIDE", "KICK", "BACK", "DOOR"],
    ["PLAY", "GROUND", "WORK", "FORCE", "FEED", "BACK", "BONE", "DRY", "DOCK", "BIRD"],
    ["RING", "SIDE", "KICK", "BACK", "BONE", "DRY", "DOCK", "BIRD", "CAGE", "MATCH"],
    ["TRACK", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE", "HEAD", "BAND", "STAND"],
  ],
  celebrities: [
    ["STAR", "POWER", "PLAY", "TIME", "LINE"],
    ["RED", "CARPET", "BOMB", "SHELL", "FISH"],
    ["FAME", "GAME", "PLAN", "TREE", "HOUSE"],
    ["FLASH", "LIGHT", "HOUSE", "HOLD", "BACK"],
    ["GOLD", "RECORD", "BOOK", "MARK", "DOWN"],
    ["BIG", "SCREEN", "PLAY", "GROUND", "WORK"],
    ["NAME", "DROP", "KICK", "BACK", "BONE"],
    ["POP", "STAR", "DUST", "BOWL", "CUT"],
    ["TALK", "SHOW", "BOAT", "HOUSE", "FIRE"],
    ["HIT", "SONG", "BIRD", "HOUSE", "HOLD"],
    ["STAR", "POWER", "PLAY", "TIME", "LINE", "BACK"],
    ["RED", "CARPET", "BOMB", "SHELL", "FISH", "BOWL"],
    ["FLASH", "LIGHT", "HOUSE", "HOLD", "BACK", "DOOR"],
    ["GOLD", "RECORD", "BOOK", "MARK", "DOWN", "HILL"],
    ["BIG", "SCREEN", "PLAY", "GROUND", "WORK", "SHOP"],
    ["NAME", "DROP", "KICK", "BACK", "BONE", "HEAD"],
    ["POP", "STAR", "DUST", "BOWL", "CUT", "BACK"],
    ["TALK", "SHOW", "BOAT", "HOUSE", "FIRE", "WALL"],
    ["HIT", "SONG", "BIRD", "HOUSE", "HOLD", "BACK"],
    ["FAME", "GAME", "PLAN", "TREE", "HOUSE", "PARTY"],
    ["FAME", "GAME", "PLAN", "TREE", "HOUSE", "WIFE", "TIME"],
    ["STAR", "POWER", "PLAY", "TIME", "LINE", "BACK", "STAGE"],
    ["RED", "CARPET", "BOMB", "SHELL", "FISH", "BOWL", "CUT"],
    ["FLASH", "LIGHT", "HOUSE", "HOLD", "BACK", "DOOR", "BELL"],
    ["GOLD", "RECORD", "BOOK", "MARK", "DOWN", "HILL", "SIDE"],
    ["BIG", "SCREEN", "PLAY", "GROUND", "WORK", "SHOP", "LIFT"],
    ["NAME", "DROP", "KICK", "BACK", "BONE", "HEAD", "BAND"],
    ["POP", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE"],
    ["TALK", "SHOW", "BOAT", "HOUSE", "FIRE", "WALL", "CLOCK"],
    ["HIT", "SONG", "BIRD", "HOUSE", "HOLD", "BACK", "DOOR"],
    ["STAR", "POWER", "PLAY", "TIME", "LINE", "BACK", "BONE", "HEAD"],
    ["RED", "CARPET", "BOMB", "SHELL", "FISH", "BOWL", "CUT", "BACK"],
    ["FLASH", "LIGHT", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP"],
    ["GOLD", "RECORD", "BOOK", "MARK", "DOWN", "HILL", "SIDE", "KICK"],
    ["BIG", "SCREEN", "PLAY", "GROUND", "WORK", "SHOP", "LIFT", "OFF"],
    ["NAME", "DROP", "KICK", "BACK", "BONE", "HEAD", "BAND", "STAND"],
    ["POP", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE", "HEAD"],
    ["TALK", "SHOW", "BOAT", "HOUSE", "FIRE", "WALL", "CLOCK", "TOWER"],
    ["HIT", "SONG", "BIRD", "HOUSE", "HOLD", "BACK", "DOOR", "BELL"],
    ["RED", "CARPET", "BOMB", "SHELL", "FISH", "BOWL", "CUT", "BACK", "DOOR"],
    ["STAR", "POWER", "PLAY", "TIME", "LINE", "BACK", "BONE", "HEAD", "BAND"],
    ["FLASH", "LIGHT", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP", "SCOTCH"],
    ["GOLD", "RECORD", "BOOK", "MARK", "DOWN", "HILL", "SIDE", "KICK", "BACK"],
    ["BIG", "SCREEN", "PLAY", "GROUND", "WORK", "SHOP", "LIFT", "OFF", "SEASON"],
    ["NAME", "DROP", "KICK", "BACK", "BONE", "HEAD", "BAND", "STAND", "STILL"],
    ["POP", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE", "HEAD", "BAND"],
    ["TALK", "SHOW", "BOAT", "HOUSE", "FIRE", "WALL", "CLOCK", "TOWER", "BLOCK"],
    ["HIT", "SONG", "BIRD", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP"],
    ["FAME", "GAME", "PLAN", "TREE", "HOUSE", "WIFE", "TIME", "LINE", "BACK", "BONE"],
    ["STAR", "POWER", "PLAY", "TIME", "LINE", "BACK", "BONE", "HEAD", "BAND", "STAND"],
    ["RED", "CARPET", "BOMB", "SHELL", "FISH", "BOWL", "CUT", "BACK", "DOOR", "BELL"],
    ["FLASH", "LIGHT", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP", "SCOTCH", "TAPE"],
    ["GOLD", "RECORD", "BOOK", "MARK", "DOWN", "HILL", "SIDE", "KICK", "BACK", "BONE"],
    ["BIG", "SCREEN", "PLAY", "GROUND", "WORK", "SHOP", "LIFT", "OFF", "SEASON", "TICKET"],
    ["NAME", "DROP", "KICK", "BACK", "BONE", "HEAD", "BAND", "STAND", "STILL", "LIFE"],
    ["POP", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE", "HEAD", "BAND", "STAND"],
    ["TALK", "SHOW", "BOAT", "HOUSE", "FIRE", "WALL", "CLOCK", "TOWER", "BLOCK", "PARTY"],
  ],
  countries: [
    ["WORLD", "CUP", "CAKE", "WALK", "WAY"],
    ["BORDER", "LINE", "BACK", "BONE", "DRY"],
    ["FLAG", "POLE", "STAR", "DUST", "BOWL"],
    ["MAP", "QUEST", "LINE", "BACK", "FIRE"],
    ["LAND", "MARK", "DOWN", "HILL", "SIDE"],
    ["STATE", "LINE", "BACK", "FIRE", "SIDE"],
    ["PASS", "PORT", "HOLE", "SALE", "PRICE"],
    ["COAST", "LINE", "BACK", "BONE", "HEAD"],
    ["TRADE", "MARK", "DOWN", "TOWN", "HOUSE"],
    ["NORTH", "STAR", "FISH", "BOWL", "CUT"],
    ["WORLD", "CUP", "CAKE", "WALK", "WAY", "SIDE"],
    ["BORDER", "LINE", "BACK", "BONE", "DRY", "DOCK"],
    ["FLAG", "POLE", "STAR", "DUST", "BOWL", "CUT"],
    ["MAP", "QUEST", "LINE", "BACK", "FIRE", "SIDE"],
    ["LAND", "MARK", "DOWN", "HILL", "SIDE", "KICK"],
    ["STATE", "LINE", "BACK", "FIRE", "SIDE", "WALK"],
    ["PASS", "PORT", "HOLE", "SALE", "PRICE", "TAG"],
    ["COAST", "LINE", "BACK", "BONE", "HEAD", "BAND"],
    ["TRADE", "MARK", "DOWN", "TOWN", "HOUSE", "PARTY"],
    ["NORTH", "STAR", "FISH", "BOWL", "CUT", "BACK"],
    ["LAND", "MARK", "DOWN", "HILL", "SIDE", "KICK", "BACK"],
    ["WORLD", "CUP", "CAKE", "WALK", "WAY", "SIDE", "LINE"],
    ["BORDER", "LINE", "BACK", "BONE", "DRY", "DOCK", "BIRD"],
    ["FLAG", "POLE", "STAR", "DUST", "BOWL", "CUT", "BACK"],
    ["MAP", "QUEST", "LINE", "BACK", "FIRE", "SIDE", "WALK"],
    ["STATE", "LINE", "BACK", "FIRE", "SIDE", "WALK", "WAY"],
    ["PASS", "PORT", "HOLE", "SALE", "PRICE", "TAG", "TEAM"],
    ["COAST", "LINE", "BACK", "BONE", "HEAD", "BAND", "STAND"],
    ["TRADE", "MARK", "DOWN", "TOWN", "HOUSE", "PARTY", "LINE"],
    ["NORTH", "STAR", "FISH", "BOWL", "CUT", "BACK", "BONE"],
    ["WORLD", "CUP", "CAKE", "WALK", "WAY", "SIDE", "LINE", "BACK"],
    ["BORDER", "LINE", "BACK", "BONE", "DRY", "DOCK", "BIRD", "CAGE"],
    ["FLAG", "POLE", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE"],
    ["MAP", "QUEST", "LINE", "BACK", "FIRE", "SIDE", "WALK", "WAY"],
    ["LAND", "MARK", "DOWN", "HILL", "SIDE", "KICK", "BACK", "BONE"],
    ["STATE", "LINE", "BACK", "FIRE", "SIDE", "WALK", "WAY", "POINT"],
    ["PASS", "PORT", "HOLE", "SALE", "PRICE", "TAG", "TEAM", "WORK"],
    ["COAST", "LINE", "BACK", "BONE", "HEAD", "BAND", "STAND", "STILL"],
    ["TRADE", "MARK", "DOWN", "TOWN", "HOUSE", "PARTY", "LINE", "BACK"],
    ["FLAG", "POLE", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE", "HEAD"],
    ["WORLD", "CUP", "CAKE", "WALK", "WAY", "SIDE", "LINE", "BACK", "BONE"],
    ["BORDER", "LINE", "BACK", "BONE", "DRY", "DOCK", "BIRD", "CAGE", "MATCH"],
    ["MAP", "QUEST", "LINE", "BACK", "FIRE", "SIDE", "WALK", "WAY", "POINT"],
    ["LAND", "MARK", "DOWN", "HILL", "SIDE", "KICK", "BACK", "BONE", "HEAD"],
    ["STATE", "LINE", "BACK", "FIRE", "SIDE", "WALK", "WAY", "POINT", "GUARD"],
    ["PASS", "PORT", "HOLE", "SALE", "PRICE", "TAG", "TEAM", "WORK", "SHOP"],
    ["COAST", "LINE", "BACK", "BONE", "HEAD", "BAND", "STAND", "STILL", "LIFE"],
    ["TRADE", "MARK", "DOWN", "TOWN", "HOUSE", "PARTY", "LINE", "BACK", "STAGE"],
    ["NORTH", "STAR", "FISH", "BOWL", "CUT", "BACK", "BONE", "HEAD", "BAND"],
    ["PASS", "PORT", "HOLE", "SALE", "PRICE", "CUT", "BACK", "BONE", "HEAD", "BAND"],
    ["WORLD", "CUP", "CAKE", "WALK", "WAY", "SIDE", "LINE", "BACK", "BONE", "HEAD"],
    ["BORDER", "LINE", "BACK", "BONE", "DRY", "DOCK", "BIRD", "CAGE", "MATCH", "BOX"],
    ["FLAG", "POLE", "STAR", "DUST", "BOWL", "CUT", "BACK", "BONE", "HEAD", "BAND"],
    ["MAP", "QUEST", "LINE", "BACK", "FIRE", "SIDE", "WALK", "WAY", "POINT", "GUARD"],
    ["LAND", "MARK", "DOWN", "HILL", "SIDE", "KICK", "BACK", "BONE", "HEAD", "BAND"],
    ["STATE", "LINE", "BACK", "FIRE", "SIDE", "WALK", "WAY", "POINT", "GUARD", "RAIL"],
    ["COAST", "LINE", "BACK", "BONE", "HEAD", "BAND", "STAND", "STILL", "LIFE", "TIME"],
    ["TRADE", "MARK", "DOWN", "TOWN", "HOUSE", "PARTY", "LINE", "BACK", "STAGE", "DOOR"],
    ["NORTH", "STAR", "FISH", "BOWL", "CUT", "BACK", "BONE", "HEAD", "BAND", "STAND"],
  ],
  cities: [
    ["CITY", "BLOCK", "CHAIN", "MAIL", "BOX"],
    ["TOWN", "HOUSE", "HOLD", "BACK", "BONE"],
    ["STREET", "LIGHT", "HOUSE", "FIRE", "TRUCK"],
    ["BRIDGE", "WORK", "BENCH", "PRESS", "BOX"],
    ["HIGH", "RISE", "FALL", "BACK", "BONE"],
    ["DOWN", "TOWN", "HOUSE", "HOLD", "BACK"],
    ["PARK", "BENCH", "MARK", "DOWN", "HILL"],
    ["SKY", "LINE", "BACK", "BONE", "FIRE"],
    ["SUBWAY", "CAR", "POOL", "SIDE", "LINE"],
    ["TOWER", "BLOCK", "CHAIN", "LINK", "UP"],
    ["CITY", "BLOCK", "CHAIN", "MAIL", "BOX", "CAR"],
    ["TOWN", "HOUSE", "HOLD", "BACK", "BONE", "DRY"],
    ["STREET", "LIGHT", "HOUSE", "FIRE", "TRUCK", "STOP"],
    ["BRIDGE", "WORK", "BENCH", "PRESS", "BOX", "CAR"],
    ["HIGH", "RISE", "FALL", "BACK", "BONE", "DRY"],
    ["DOWN", "TOWN", "HOUSE", "HOLD", "BACK", "DOOR"],
    ["PARK", "BENCH", "MARK", "DOWN", "HILL", "SIDE"],
    ["SKY", "LINE", "BACK", "BONE", "FIRE", "SIDE"],
    ["SUBWAY", "CAR", "POOL", "SIDE", "LINE", "BACK"],
    ["TOWER", "BLOCK", "CHAIN", "LINK", "UP", "GRADE"],
    ["STREET", "LIGHT", "HOUSE", "FIRE", "TRUCK", "STOP", "SIGN"],
    ["CITY", "BLOCK", "CHAIN", "MAIL", "BOX", "CAR", "POOL"],
    ["TOWN", "HOUSE", "HOLD", "BACK", "BONE", "DRY", "DOCK"],
    ["BRIDGE", "WORK", "BENCH", "PRESS", "BOX", "CAR", "POOL"],
    ["HIGH", "RISE", "FALL", "BACK", "BONE", "DRY", "DOCK"],
    ["DOWN", "TOWN", "HOUSE", "HOLD", "BACK", "DOOR", "BELL"],
    ["PARK", "BENCH", "MARK", "DOWN", "HILL", "SIDE", "WALK"],
    ["SKY", "LINE", "BACK", "BONE", "FIRE", "SIDE", "WALK"],
    ["SUBWAY", "CAR", "POOL", "SIDE", "LINE", "BACK", "BONE"],
    ["TOWER", "BLOCK", "CHAIN", "LINK", "UP", "GRADE", "SCHOOL"],
    ["CITY", "BLOCK", "CHAIN", "MAIL", "BOX", "CAR", "POOL", "SIDE"],
    ["TOWN", "HOUSE", "HOLD", "BACK", "BONE", "DRY", "DOCK", "BIRD"],
    ["STREET", "LIGHT", "HOUSE", "FIRE", "TRUCK", "STOP", "SIGN", "LANGUAGE"],
    ["BRIDGE", "WORK", "BENCH", "PRESS", "BOX", "CAR", "POOL", "SIDE"],
    ["HIGH", "RISE", "FALL", "BACK", "BONE", "DRY", "DOCK", "SIDE"],
    ["DOWN", "TOWN", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP"],
    ["PARK", "BENCH", "MARK", "DOWN", "HILL", "SIDE", "WALK", "WAY"],
    ["SKY", "LINE", "BACK", "BONE", "FIRE", "SIDE", "WALK", "WAY"],
    ["SUBWAY", "CAR", "POOL", "SIDE", "LINE", "BACK", "BONE", "HEAD"],
    ["TOWER", "BLOCK", "CHAIN", "LINK", "UP", "GRADE", "SCHOOL", "HOUSE"],
    ["TOWER", "BLOCK", "CHAIN", "LINK", "UP", "GRADE", "SCHOOL", "HOUSE", "HOLD"],
    ["CITY", "BLOCK", "CHAIN", "MAIL", "BOX", "CAR", "POOL", "SIDE", "LINE"],
    ["TOWN", "HOUSE", "HOLD", "BACK", "BONE", "DRY", "DOCK", "BIRD", "CAGE"],
    ["STREET", "LIGHT", "HOUSE", "FIRE", "TRUCK", "STOP", "SIGN", "LANGUAGE", "ARTS"],
    ["BRIDGE", "WORK", "BENCH", "PRESS", "BOX", "CAR", "POOL", "SIDE", "LINE"],
    ["HIGH", "RISE", "FALL", "BACK", "BONE", "DRY", "DOCK", "SIDE", "LINE"],
    ["DOWN", "TOWN", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP", "SCOTCH"],
    ["PARK", "BENCH", "MARK", "DOWN", "HILL", "SIDE", "WALK", "WAY", "POINT"],
    ["SKY", "LINE", "BACK", "BONE", "FIRE", "SIDE", "WALK", "WAY", "POINT"],
    ["SUBWAY", "CAR", "POOL", "SIDE", "LINE", "BACK", "BONE", "HEAD", "BAND"],
    ["STREET", "LIGHT", "HOUSE", "FIRE", "SIDE", "WALK", "WAY", "POINT", "GUARD", "RAIL"],
    ["CITY", "BLOCK", "CHAIN", "MAIL", "BOX", "CAR", "POOL", "SIDE", "LINE", "BACK"],
    ["TOWN", "HOUSE", "HOLD", "BACK", "BONE", "DRY", "DOCK", "BIRD", "CAGE", "MATCH"],
    ["BRIDGE", "WORK", "BENCH", "PRESS", "BOX", "CAR", "POOL", "SIDE", "LINE", "BACK"],
    ["HIGH", "RISE", "FALL", "BACK", "BONE", "DRY", "DOCK", "SIDE", "LINE", "BACK"],
    ["DOWN", "TOWN", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP", "SCOTCH", "TAPE"],
    ["PARK", "BENCH", "MARK", "DOWN", "HILL", "SIDE", "WALK", "WAY", "POINT", "GUARD"],
    ["SKY", "LINE", "BACK", "BONE", "FIRE", "SIDE", "WALK", "WAY", "POINT", "GUARD"],
    ["SUBWAY", "CAR", "POOL", "SIDE", "LINE", "BACK", "BONE", "HEAD", "BAND", "STAND"],
    ["TOWER", "BLOCK", "CHAIN", "LINK", "UP", "GRADE", "SCHOOL", "HOUSE", "HOLD", "BACK"],
  ],
  minecraftMobs: [
    ["BLOCK", "HEAD", "BAND", "STAND", "STILL"],
    ["CAVE", "MAN", "HOLE", "PUNCH", "LINE"],
    ["IRON", "ORE", "MINE", "CRAFT", "WORK"],
    ["BONE", "MEAL", "WORM", "HOLE", "SHOT"],
    ["STONE", "COLD", "FRONT", "LINE", "BACK"],
    ["LAVA", "FLOW", "CHART", "HOUSE", "HOLD"],
    ["SAND", "CASTLE", "ROCK", "BAND", "WIDTH"],
    ["SLIME", "BALL", "PARK", "BENCH", "PRESS"],
    ["DARK", "ROOM", "MATE", "SHIP", "WRECK"],
    ["SPAWN", "POINT", "GUARD", "RAIL", "ROAD"],
    ["BLOCK", "HEAD", "BAND", "STAND", "STILL", "LIFE"],
    ["CAVE", "MAN", "HOLE", "PUNCH", "LINE", "BACK"],
    ["BONE", "MEAL", "WORM", "HOLE", "SHOT", "CLOCK"],
    ["STONE", "COLD", "FRONT", "LINE", "BACK", "DOOR"],
    ["LAVA", "FLOW", "CHART", "HOUSE", "HOLD", "BACK"],
    ["SAND", "CASTLE", "ROCK", "BAND", "WIDTH", "DRAW"],
    ["SLIME", "BALL", "PARK", "BENCH", "PRESS", "BOX"],
    ["DARK", "ROOM", "MATE", "SHIP", "WRECK", "AGE"],
    ["SPAWN", "POINT", "GUARD", "RAIL", "ROAD", "BLOCK"],
    ["IRON", "ORE", "MINE", "CRAFT", "WORK", "SHOP"],
    ["IRON", "ORE", "MINE", "CRAFT", "WORK", "BENCH", "MARK"],
    ["BLOCK", "HEAD", "BAND", "STAND", "STILL", "LIFE", "TIME"],
    ["CAVE", "MAN", "HOLE", "PUNCH", "LINE", "BACK", "BONE"],
    ["BONE", "MEAL", "WORM", "HOLE", "SHOT", "CLOCK", "TOWER"],
    ["STONE", "COLD", "FRONT", "LINE", "BACK", "DOOR", "BELL"],
    ["LAVA", "FLOW", "CHART", "HOUSE", "HOLD", "BACK", "DOOR"],
    ["SLIME", "BALL", "PARK", "BENCH", "PRESS", "BOX", "CAR"],
    ["DARK", "ROOM", "MATE", "SHIP", "WRECK", "AGE", "GROUP"],
    ["SPAWN", "POINT", "GUARD", "RAIL", "ROAD", "BLOCK", "PARTY"],
    ["IRON", "ORE", "MINE", "CRAFT", "WORK", "SHOP", "LIFT"],
    ["BLOCK", "HEAD", "BAND", "STAND", "STILL", "LIFE", "TIME", "LINE"],
    ["CAVE", "MAN", "HOLE", "PUNCH", "LINE", "BACK", "BONE", "DRY"],
    ["BONE", "MEAL", "WORM", "HOLE", "SHOT", "CLOCK", "TOWER", "BLOCK"],
    ["STONE", "COLD", "FRONT", "LINE", "BACK", "DOOR", "BELL", "HOP"],
    ["LAVA", "FLOW", "CHART", "HOUSE", "HOLD", "BACK", "DOOR", "BELL"],
    ["SAND", "CASTLE", "ROCK", "BAND", "STAND", "STILL", "LIFE", "TIME"],
    ["SLIME", "BALL", "PARK", "BENCH", "PRESS", "BOX", "CAR", "POOL"],
    ["DARK", "ROOM", "MATE", "SHIP", "WRECK", "AGE", "GROUP", "CHAT"],
    ["SPAWN", "POINT", "GUARD", "RAIL", "ROAD", "BLOCK", "PARTY", "LINE"],
    ["BONE", "MEAL", "WORM", "HOLE", "PUNCH", "LINE", "BACK", "BONE", "DRY"],
    ["BLOCK", "HEAD", "BAND", "STAND", "STILL", "LIFE", "TIME", "LINE", "BACK"],
    ["CAVE", "MAN", "HOLE", "PUNCH", "LINE", "BACK", "BONE", "DRY", "DOCK"],
    ["STONE", "COLD", "FRONT", "LINE", "BACK", "DOOR", "BELL", "HOP", "SCOTCH"],
    ["LAVA", "FLOW", "CHART", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP"],
    ["SAND", "CASTLE", "ROCK", "BAND", "STAND", "STILL", "LIFE", "TIME", "LINE"],
    ["SLIME", "BALL", "PARK", "BENCH", "PRESS", "BOX", "CAR", "POOL", "SIDE"],
    ["DARK", "ROOM", "MATE", "SHIP", "WRECK", "AGE", "GROUP", "CHAT", "ROOM"],
    ["SPAWN", "POINT", "GUARD", "RAIL", "ROAD", "BLOCK", "PARTY", "LINE", "BACK"],
    ["IRON", "ORE", "MINE", "CRAFT", "WORK", "SHOP", "LIFT", "OFF", "SEASON"],
    ["IRON", "ORE", "MINE", "CRAFT", "WORK", "BENCH", "MARK", "DOWN", "HILL", "SIDE"],
    ["BLOCK", "HEAD", "BAND", "STAND", "STILL", "LIFE", "TIME", "LINE", "BACK", "BONE"],
    ["CAVE", "MAN", "HOLE", "PUNCH", "LINE", "BACK", "BONE", "DRY", "DOCK", "BIRD"],
    ["BONE", "MEAL", "WORM", "HOLE", "SHOT", "CLOCK", "TOWER", "BLOCK", "PARTY", "LINE"],
    ["STONE", "COLD", "FRONT", "LINE", "BACK", "DOOR", "BELL", "HOP", "SCOTCH", "TAPE"],
    ["LAVA", "FLOW", "CHART", "HOUSE", "HOLD", "BACK", "DOOR", "BELL", "HOP", "SCOTCH"],
    ["SAND", "CASTLE", "ROCK", "BAND", "STAND", "STILL", "LIFE", "TIME", "LINE", "BACK"],
    ["SLIME", "BALL", "PARK", "BENCH", "PRESS", "BOX", "CAR", "POOL", "SIDE", "LINE"],
    ["DARK", "ROOM", "MATE", "SHIP", "WRECK", "AGE", "GROUP", "CHAT", "ROOM", "MATE"],
    ["SPAWN", "POINT", "GUARD", "RAIL", "ROAD", "BLOCK", "PARTY", "LINE", "BACK", "BONE"],
  ],
};

export const chainCategories = Object.keys(chainWordBank);

export const chainCategoryLabels: Record<string, string> = { ...gameCategoryLabels };

// Legacy flat list for backwards compat — combines all categorized chains
export const chainWordBankFlat: string[][] = Object.values(chainWordBank).flat();

// ── Password word bank (categorized) ────────────────────
// Words that work well with one-word clues, themed around each category.
export const passwordWordBank: Record<string, string[]> = {
  animals: [
    "Dog", "Cat", "Elephant", "Lion", "Tiger", "Bear", "Giraffe", "Zebra", "Kangaroo", "Penguin",
    "Horse", "Wolf", "Fox", "Panda", "Rabbit", "Koala", "Cheetah", "Dolphin", "Monkey", "Owl",
    "Eagle", "Parrot", "Falcon", "Otter", "Walrus", "Shark", "Whale", "Octopus", "Turtle", "Frog",
    "Snake", "Spider", "Scorpion", "Bat", "Hamster", "Raccoon", "Skunk", "Moose", "Deer", "Beaver",
  ],
  moviesAndShows: [
    "Popcorn", "Screen", "Ticket", "Trailer", "Script", "Actor", "Camera", "Director", "Sequel", "Scene",
    "Stunt", "Villain", "Hero", "Monster", "Robot", "Alien", "Zombie", "Ghost", "Wizard", "Pirate",
    "Knight", "Dragon", "Throne", "Crown", "Sword", "Shield", "Castle", "Dungeon", "Prison", "Chase",
    "Heist", "Disguise", "Plot", "Twist", "Cliffhanger", "Remake", "Premiere", "Oscar", "Spotlight", "Curtain",
  ],
  disneyAndPixar: [
    "Princess", "Castle", "Wand", "Crown", "Magic", "Mirror", "Lamp", "Genie", "Carpet", "Slipper",
    "Poison", "Apple", "Beast", "Rose", "Candle", "Clock", "Teapot", "Snowflake", "Tiara", "Tower",
    "Lantern", "Compass", "Treasure", "Island", "Jungle", "Dragon", "Toy", "Cowboy", "Spaceman", "Fish",
    "Balloon", "House", "Robot", "Monster", "Door", "Rat", "Kitchen", "Superhero", "Emotion", "Memory",
  ],
  fpsGames: [
    "Sniper", "Grenade", "Shield", "Rocket", "Helmet", "Bullet", "Target", "Scope", "Ammo", "Pistol",
    "Shotgun", "Rifle", "Turret", "Bunker", "Trench", "Medic", "Armor", "Bomb", "Hacker", "Drone",
    "Missile", "Tank", "Crosshair", "Trigger", "Reload", "Magazine", "Silencer", "Flashbang", "Barricade", "Fortress",
    "Radar", "Compass", "Parachute", "Jetpack", "Laser", "Plasma", "Cannon", "Bayonet", "Knife", "Camo",
  ],
  otherGames: [
    "Diamond", "Pickaxe", "Chest", "Potion", "Shield", "Sword", "Portal", "Dungeon", "Dragon", "Boss",
    "Treasure", "Crystal", "Inventory", "Crafting", "Skeleton", "Zombie", "Creeper", "Enchantment", "Fireball", "Arrow",
    "Helmet", "Boots", "Village", "Castle", "Tower", "Bridge", "Mushroom", "Torch", "Lantern", "Compass",
    "Saddle", "Anvil", "Cauldron", "Beacon", "Banner", "Fossil", "Trophy", "Medal", "Crown", "Emerald",
  ],
  food: [
    "Pizza", "Burger", "Pasta", "Sushi", "Taco", "Steak", "Pancake", "Waffle", "Omelette", "Sandwich",
    "Burrito", "Lasagna", "Dumpling", "Noodle", "Pretzel", "Croissant", "Muffin", "Cookie", "Brownie", "Cupcake",
    "Donut", "Popcorn", "Nacho", "Salad", "Soup", "Chowder", "Curry", "Kebab", "Falafel", "Hummus",
    "Avocado", "Banana", "Mango", "Pineapple", "Coconut", "Strawberry", "Blueberry", "Watermelon", "Grape", "Cherry",
  ],
  drinks: [
    "Coffee", "Latte", "Espresso", "Cappuccino", "Mocha", "Smoothie", "Milkshake", "Lemonade", "Juice", "Soda",
    "Tea", "Cocoa", "Cider", "Punch", "Slushie", "Frappe", "Bubble", "Matcha", "Chai", "Kombucha",
    "Water", "Sparkling", "Tonic", "Ginger", "Mango", "Peach", "Strawberry", "Lime", "Cherry", "Vanilla",
    "Caramel", "Chocolate", "Whipped", "Cream", "Sugar", "Honey", "Mint", "Lavender", "Cinnamon", "Syrup",
  ],
  restaurants: [
    "Menu", "Table", "Booth", "Counter", "Kitchen", "Chef", "Waiter", "Tip", "Receipt", "Napkin",
    "Ketchup", "Mustard", "Straw", "Tray", "Grill", "Oven", "Fryer", "Blender", "Spatula", "Apron",
    "Drive", "Takeout", "Delivery", "Franchise", "Logo", "Mascot", "Coupon", "Combo", "Value", "Special",
    "Breakfast", "Lunch", "Dinner", "Snack", "Dessert", "Appetizer", "Salad", "Fries", "Shake", "Sundae",
  ],
  carBrands: [
    "Engine", "Wheel", "Tire", "Steering", "Bumper", "Hood", "Trunk", "Mirror", "Headlight", "Exhaust",
    "Turbo", "Diesel", "Hybrid", "Convertible", "Sedan", "Coupe", "Hatchback", "Pickup", "Jeep", "Mustang",
    "Dashboard", "Speedometer", "Clutch", "Brake", "Accelerator", "Windshield", "Antenna", "Sunroof", "Spoiler", "Chrome",
    "Garage", "Highway", "Racetrack", "Pit", "Finish", "Drift", "Burnout", "Horsepower", "Torque", "Cylinder",
  ],
  luxuryBrands: [
    "Diamond", "Pearl", "Sapphire", "Ruby", "Emerald", "Gold", "Silver", "Platinum", "Crystal", "Velvet",
    "Silk", "Cashmere", "Leather", "Satin", "Marble", "Ivory", "Champagne", "Caviar", "Lobster", "Truffle",
    "Perfume", "Cologne", "Tiara", "Necklace", "Bracelet", "Watch", "Wallet", "Handbag", "Sunglasses", "Heels",
    "Runway", "Boutique", "Mansion", "Yacht", "Limousine", "Penthouse", "Suite", "Chandelier", "Fountain", "Staircase",
  ],
  sports: [
    "Soccer", "Basketball", "Baseball", "Football", "Tennis", "Golf", "Hockey", "Volleyball", "Cricket", "Rugby",
    "Trophy", "Medal", "Whistle", "Referee", "Stadium", "Goalpost", "Racket", "Glove", "Helmet", "Cleats",
    "Dribble", "Tackle", "Sprint", "Hurdle", "Javelin", "Discus", "Pole", "Archery", "Kayak", "Surfboard",
    "Scoreboard", "Halftime", "Overtime", "Penalty", "Foul", "Champion", "Relay", "Marathon", "Triathlon", "Podium",
  ],
  celebrities: [
    "Paparazzi", "Autograph", "Interview", "Mansion", "Limousine", "Award", "Album", "Concert", "Spotlight", "Stage",
    "Microphone", "Guitar", "Piano", "Drum", "Ticket", "Poster", "Magazine", "Selfie", "Tattoo", "Fashion",
    "Perfume", "Sunglasses", "Bodyguard", "Private", "Yacht", "Premier", "Debut", "Encore", "Makeup", "Stylist",
    "Gossip", "Headline", "Scandal", "Red", "Carpet", "Throne", "Crown", "Empire", "Fortune", "Legacy",
  ],
  countries: [
    "Passport", "Flag", "Border", "Capital", "Mountain", "River", "Ocean", "Desert", "Jungle", "Island",
    "Temple", "Palace", "Castle", "Monument", "Pyramid", "Tower", "Bridge", "Market", "Festival", "Carnival",
    "Currency", "Language", "Cuisine", "Spice", "Tea", "Coffee", "Silk", "Bamboo", "Coconut", "Volcano",
    "Glacier", "Canyon", "Waterfall", "Glacier", "Tundra", "Safari", "Coral", "Lagoon", "Reef", "Aurora",
  ],
  cities: [
    "Skyscraper", "Subway", "Taxi", "Bridge", "Fountain", "Statue", "Museum", "Library", "Cathedral", "Theater",
    "Sidewalk", "Alley", "Boulevard", "Avenue", "Highway", "Tunnel", "Rooftop", "Penthouse", "Balcony", "Terrace",
    "Market", "Bakery", "Cafe", "Nightclub", "Gallery", "Studio", "Warehouse", "Loft", "Harbor", "Pier",
    "Lighthouse", "Clock", "Bench", "Lamp", "Mailbox", "Hydrant", "Manhole", "Crosswalk", "Skyline", "Neon",
  ],
  minecraftMobs: [
    "Creeper", "Zombie", "Skeleton", "Enderman", "Spider", "Villager", "Witch", "Slime", "Blaze", "Ghast",
    "Piglin", "Golem", "Pillager", "Warden", "Axolotl", "Bee", "Bat", "Wolf", "Cat", "Fox",
    "Pickaxe", "Sword", "Bow", "Trident", "Shield", "Armor", "Potion", "Enchantment", "Anvil", "Beacon",
    "Diamond", "Emerald", "Redstone", "Obsidian", "Netherite", "Portal", "Dungeon", "Fortress", "Village", "Stronghold",
  ],
};

export const passwordCategories = Object.keys(passwordWordBank);

export const passwordCategoryLabels: Record<string, string> = { ...gameCategoryLabels };
