// Example: imposterWords.ts
export const imposterCategories = {
  Animals: [  "Aardvark", "Aardwolf", "Albatross", "Alligator", "Alpaca", "Anaconda", "Angelfish", "Ant", "Anteater", "Antelope",
    "Armadillo", "Baboon", "Badger", "Barracuda", "Bat", "Bear", "Beaver", "Bee", "Bison", "Boar",
    "Bobcat", "Buffalo", "Butterfly", "Camel", "Capybara", "Caribou", "Cassowary", "Cat", "Caterpillar", "Cattle",
    "Chameleon", "Cheetah", "Chicken", "Chimpanzee", "Chinchilla", "Clam", "Cobra", "Cockroach", "Cod", "Condor",
    "Cougar", "Cow", "Coyote", "Crab", "Crane", "Crocodile", "Crow", "Cuckoo", "Deer", "Dingo",
    "Dinosaur", "Dog", "Dolphin", "Donkey", "Dove", "Dragonfly", "Duck", "Eagle", "Echidna", "Eel",
    "Egret", "Elephant", "Elk", "Emu", "Falcon", "Ferret", "Finch", "Firefly", "Fish", "Flamingo",
    "Fly", "Fox", "Frog", "Gazelle", "Gecko", "Gerbil", "Giraffe", "Goat", "Goldfish", "Goose",
    "Gopher", "Gorilla", "Grasshopper", "Grouse", "Guanaco", "Guinea Pig", "Gull", "Hamster", "Hare", "Hawk",
    "Hedgehog", "Heron", "Herring", "Hippopotamus", "Hornet", "Horse", "Hummingbird", "Hyena", "Ibex", "Ibis",
    "Iguana", "Impala", "Jackal", "Jaguar", "Jellyfish", "Kangaroo", "Kingfisher", "Koala", "Komodo Dragon", "Kookaburra",
    "Kudu", "Ladybug", "Lapwing", "Lark", "Leopard", "Lion", "Lizard", "Llama", "Lobster", "Locust",
    "Lynx", "Macaw", "Magpie", "Mallard", "Manatee", "Mandrill", "Mantis", "Marten", "Meerkat", "Mink",
    "Mole", "Mongoose", "Monkey", "Moose", "Mosquito", "Moth", "Mouse", "Mule", "Narwhal", "Newt",
    "Nightingale", "Octopus", "Okapi", "Opossum", "Orangutan", "Orca", "Ostrich", "Otter", "Owl", "Ox",
    "Oyster", "Panda", "Panther", "Parrot", "Partridge", "Peacock", "Pelican", "Penguin", "Pheasant", "Pig",
    "Pigeon", "Platypus", "Polar Bear", "Porcupine", "Porpoise", "Prairie Dog", "Prawn", "Puffin", "Puma", "Quail",
    "Quokka", "Rabbit", "Raccoon", "Ram", "Rat", "Rattlesnake", "Raven", "Red Panda", "Reindeer", "Rhinoceros",
    "Roadrunner", "Robin", "Rooster", "Salamander", "Salmon", "Sand Dollar", "Sandpiper", "Sardine", "Scorpion", "Seahorse",
    "Seal", "Shark", "Sheep", "Shrimp", "Skunk", "Sloth", "Snail", "Snake", "Sparrow", "Spider",
    "Spoonbill", "Squid", "Squirrel", "Starfish", "Stingray", "Stork", "Swallow", "Swan", "Tapir", "Tarantula",
    "Termite", "Tiger", "Toad", "Toucan", "Turkey", "Turtle", "Viper", "Vulture", "Wallaby", "Walrus",
    "Wasp", "Weasel", "Whale", "Wildcat", "Wolf", "Wolverine", "Wombat", "Woodpecker", "Worm", "Wren",
    "Yak", "Zebra", "Zebu", "Zorilla", "Zorse", "African Buffalo", "African Elephant", "African Grey Parrot", "African Wild Dog", "American Alligator",
    "American Bison", "American Robin", "Arctic Fox", "Arctic Hare", "Arctic Wolf", "Asian Elephant", "Atlantic Puffin", "Australian Shepherd", "Axolotl", "Bactrian Camel",
    "Bald Eagle", "Barn Owl", "Barn Swallow", "Barramundi", "Basilisk Lizard", "Basset Hound", "Batfish", "Beagle", "Bearded Dragon", "Beetle",
    "Beluga Whale", "Bengal Tiger", "Binturong", "Bird of Paradise", "Black Bear", "Black Mamba", "Black Widow Spider", "Blue Jay", "Blue Whale", "Boa Constrictor",
    "Bobolink", "Bonobo", "Box Jellyfish", "Box Turtle", "Budgerigar", "Bull", "Bullfrog", "Bumblebee", "Butterflyfish", "Caiman",
    "Camel Spider", "Canary", "Capuchin Monkey", "Caracal", "Carp", "Cassowary", "Catfish", "Caterpillar", "Centipede", "Chamois",
    "Cheetah", "Chickadee", "Chihuahua", "Chinchilla", "Chipmunk", "Cicada", "Clownfish", "Coati", "Cobra", "Cockatoo",
    "Cocker Spaniel", "Codfish", "Collie", "Common Loon", "Coot", "Cormorant", "Cougar", "Coyote", "Crab", "Crane",
    "Crested Penguin", "Crocodile", "Cuckoo", "Cuscus", "Cuttlefish", "Dachshund", "Dalmatian", "Dart Frog", "Deer", "Dingo",
    "Dodo", "Dolphin", "Donkey", "Dormouse", "Dragonfly", "Duck", "Dugong", "Eagle", "Earthworm", "Echidna",
    "Eel", "Egret", "Elephant Seal", "Elk", "Emperor Penguin", "Emu", "Falcon", "Fennec Fox", "Ferret", "Finch",
    "Flounder", "Flying Fish", "Flying Squirrel", "Fossa", "Foxhound", "Frigatebird", "Fruit Bat", "Gaur", "Gazelle", "Gecko"],
  Movies: ["Titanic", "Inception", "Avatar", "Jaws", "Rocky", "Frozen", "Gladiator", "Shrek", "Up", "Matrix",   "The Shawshank Redemption", "The Godfather", "The Dark Knight", "The Godfather Part II", "12 Angry Men",
    "Schindler's List", "The Lord of the Rings: The Return of the King", "Pulp Fiction", "The Good, the Bad and the Ugly", "Fight Club",
    "Forrest Gump", "Inception", "The Lord of the Rings: The Fellowship of the Ring", "Star Wars: Episode V - The Empire Strikes Back", "The Matrix",
    "Goodfellas", "One Flew Over the Cuckoo's Nest", "Seven Samurai", "Se7en", "City of God",
    "The Silence of the Lambs", "It's a Wonderful Life", "Life Is Beautiful", "The Usual Suspects", "Léon: The Professional",
    "Saving Private Ryan", "Spirited Away", "Interstellar", "The Green Mile", "Parasite",
    "The Pianist", "The Lion King", "Terminator 2: Judgment Day", "Back to the Future", "American History X",
    "Modern Times", "Psycho", "Gladiator", "City Lights", "The Departed",
    "Whiplash", "The Intouchables", "The Prestige", "Casablanca", "Once Upon a Time in the West",
    "Grave of the Fireflies", "Rear Window", "Alien", "Apocalypse Now", "Memento",
    "Raiders of the Lost Ark", "The Great Dictator", "Django Unchained", "The Lives of Others", "Paths of Glory",
    "WALL·E", "Sunset Blvd.", "The Shining", "Witness for the Prosecution", "Avengers: Infinity War",
    "Oldboy", "Princess Mononoke", "Dr. Strangelove", "The Dark Knight Rises", "Aliens",
    "Once Upon a Time in America", "Coco", "Your Name", "Braveheart", "Das Boot",
    "Avengers: Endgame", "Toy Story", "3 Idiots", "Inglourious Basterds", "Amélie",
    "Good Will Hunting", "Requiem for a Dream", "Toy Story 3", "Reservoir Dogs", "Eternal Sunshine of the Spotless Mind",
    "Capernaum", "Dangal", "Like Stars on Earth", "2001: A Space Odyssey", "Citizen Kane",
    "Singin' in the Rain", "Lawrence of Arabia", "Vertigo", "North by Northwest", "M",
    "The Hunt", "A Clockwork Orange", "Double Indemnity", "Full Metal Jacket", "Bicycle Thieves",
    "The Kid", "The Father", "Snatch", "Scarface", "Taxi Driver",
    "The Sting", "The Apartment", "Metropolis", "Joker", "The Truman Show",
    "The Sixth Sense", "The Thing", "No Country for Old Men", "Finding Nemo", "There Will Be Blood",
    "Raging Bull", "Chinatown", "The Bridge on the River Kwai", "Pan's Labyrinth", "My Neighbor Totoro",
    "The Seventh Seal", "The Elephant Man", "The Wolf of Wall Street", "V for Vendetta", "Inside Out",
    "The Gold Rush", "Blade Runner", "The Grand Budapest Hotel", "12 Years a Slave", "The Big Lebowski",
    "Gone Girl", "The Handmaiden", "Room", "The Imitation Game", "The Social Network",
    "The Revenant", "The King's Speech", "Slumdog Millionaire", "Black Swan", "La La Land",
    "The Shape of Water", "The Artist", "Argo", "Birdman", "The Theory of Everything",
    "The Hateful Eight", "Brooklyn", "Spotlight", "Mad Max: Fury Road", "The Martian",
    "Ex Machina", "Arrival", "Moonlight", "Manchester by the Sea", "Hell or High Water",
    "Lion", "Hidden Figures", "Hacksaw Ridge", "Fences", "The Big Short",
    "Bridge of Spies", "The Danish Girl", "The Post", "Darkest Hour", "Three Billboards Outside Ebbing, Missouri",
    "Call Me by Your Name", "Lady Bird", "Phantom Thread", "The Shape of Water", "Get Out",
    "Dunkirk", "The Florida Project", "The Disaster Artist", "I, Tonya", "Molly's Game",
    "The Favourite", "Bohemian Rhapsody", "Green Book", "Vice", "BlacKkKlansman",
    "Roma", "A Star Is Born", "The Ballad of Buster Scruggs", "Cold War", "First Man",
    "If Beale Street Could Talk", "Can You Ever Forgive Me?", "The Mule", "Mary Poppins Returns", "The Wife",
    "The Irishman", "Marriage Story", "1917", "Once Upon a Time in Hollywood", "Jojo Rabbit",
    "Parasite", "Ford v Ferrari", "Joker", "Little Women", "The Two Popes",
    "Knives Out", "Uncut Gems", "The Lighthouse", "Portrait of a Lady on Fire", "The Farewell",
    "Soul", "Nomadland", "Promising Young Woman", "Minari", "Sound of Metal",
    "The Trial of the Chicago 7", "Mank", "One Night in Miami", "The Father", "Judas and the Black Messiah",
    "The Mitchells vs. The Machines", "Luca", "The French Dispatch", "Dune", "No Time to Die",
    "Shang-Chi and the Legend of the Ten Rings", "Eternals", "Spider-Man: No Way Home", "The Power of the Dog", "West Side Story",
    "Belfast", "Licorice Pizza", "King Richard", "Don't Look Up", "Nightmare Alley",
    "CODA", "Drive My Car", "The Lost Daughter", "Being the Ricardos", "Tick, Tick... Boom!",
    "The Batman", "Everything Everywhere All at Once", "Top Gun: Maverick", "The Northman", "The Whale",
    "Avatar: The Way of Water", "The Fabelmans", "TÁR", "Women Talking", "All Quiet on the Western Front",
    "Triangle of Sadness", "The Banshees of Inisherin", "Elvis", "The Menu", "Glass Onion: A Knives Out Mystery",
    "RRR", "Nope", "The Woman King", "Babylon", "The Pale Blue Eye",
    "Empire of Light", "She Said", "The Son", "White Noise", "Till",
    "The Wonder", "Aftersun", "Decision to Leave", "The Good Nurse", "The Inspection",
    "Armageddon Time", "The Lost City", "Sonic the Hedgehog 2", "Jurassic World Dominion", "Thor: Love and Thunder",
    "Black Adam", "The Batman", "Spider"],
  Food: ["Pizza", "Burger", "Sushi", "Pasta", "Taco", "Salad", "Steak", "Apple", "Banana", "Carrot",  "Apple", "Banana", "Orange", "Grapes", "Strawberry", "Blueberry", "Raspberry", "Blackberry", "Pineapple", "Mango",
    "Papaya", "Watermelon", "Cantaloupe", "Honeydew", "Kiwi", "Peach", "Plum", "Cherry", "Apricot", "Nectarine",
    "Lemon", "Lime", "Coconut", "Pomegranate", "Guava", "Passion Fruit", "Dragon Fruit", "Lychee", "Fig", "Date",
    "Avocado", "Tomato", "Cucumber", "Carrot", "Celery", "Lettuce", "Spinach", "Kale", "Broccoli", "Cauliflower",
    "Brussels Sprouts", "Cabbage", "Zucchini", "Eggplant", "Bell Pepper", "Chili Pepper", "Onion", "Garlic", "Leek", "Shallot",
    "Potato", "Sweet Potato", "Yam", "Corn", "Peas", "Green Beans", "Asparagus", "Artichoke", "Beet", "Radish",
    "Turnip", "Parsnip", "Rutabaga", "Mushroom", "Okra", "Pumpkin", "Squash", "Acorn Squash", "Butternut Squash", "Spaghetti Squash",
    "Rice", "Brown Rice", "White Rice", "Wild Rice", "Quinoa", "Barley", "Oats", "Millet", "Couscous", "Polenta",
    "Bread", "Whole Wheat Bread", "White Bread", "Sourdough Bread", "Rye Bread", "Pita Bread", "Naan", "Bagel", "English Muffin", "Croissant",
    "Pancake", "Waffle", "French Toast", "Muffin", "Biscuit", "Scone", "Donut", "Cake", "Cupcake", "Brownie",
    "Cookie", "Chocolate Chip Cookie", "Oatmeal Cookie", "Peanut Butter Cookie", "Sugar Cookie", "Snickerdoodle", "Macaron", "Macaroon", "Shortbread", "Gingerbread",
    "Ice Cream", "Vanilla Ice Cream", "Chocolate Ice Cream", "Strawberry Ice Cream", "Mint Chocolate Chip Ice Cream", "Cookies and Cream Ice Cream", "Butter Pecan Ice Cream", "Rocky Road Ice Cream", "Neapolitan Ice Cream", "Gelato",
    "Sorbet", "Frozen Yogurt", "Popsicle", "Sherbet", "Milkshake", "Smoothie", "Yogurt", "Greek Yogurt", "Fruit Yogurt", "Plain Yogurt",
    "Cheese", "Cheddar Cheese", "Mozzarella Cheese", "Swiss Cheese", "Parmesan Cheese", "Blue Cheese", "Goat Cheese", "Brie Cheese", "Camembert Cheese", "Feta Cheese",
    "Cream Cheese", "Cottage Cheese", "Ricotta Cheese", "Provolone Cheese", "Monterey Jack Cheese", "Colby Cheese", "Havarti Cheese", "Gouda Cheese", "Limburger Cheese", "Paneer",
    "Milk", "Whole Milk", "Skim Milk", "2% Milk", "1% Milk", "Almond Milk", "Soy Milk", "Rice Milk", "Oat Milk", "Coconut Milk",
    "Butter", "Margarine", "Ghee", "Lard", "Shortening", "Olive Oil", "Canola Oil", "Vegetable Oil", "Peanut Oil", "Sesame Oil",
    "Sunflower Oil", "Corn Oil", "Palm Oil", "Avocado Oil", "Flaxseed Oil", "Walnut Oil", "Grapeseed Oil", "Safflower Oil", "Mustard Oil", "Soybean Oil",
    "Beef", "Steak", "Ground Beef", "Roast Beef", "Beef Ribs", "Beef Brisket", "Beef Jerky", "Veal", "Lamb", "Pork",
    "Pork Chops", "Bacon", "Ham", "Sausage", "Hot Dog", "Pork Ribs", "Pulled Pork", "Pork Tenderloin", "Pork Belly", "Prosciutto",
    "Chicken", "Chicken Breast", "Chicken Thigh", "Chicken Wing", "Chicken Drumstick", "Chicken Nugget", "Fried Chicken", "Grilled Chicken", "Roast Chicken", "Chicken Tenders",
    "Turkey", "Turkey Breast", "Ground Turkey", "Turkey Bacon", "Turkey Sausage", "Duck", "Goose", "Quail", "Pheasant", "Cornish Hen",
    "Fish", "Salmon", "Tuna", "Cod", "Haddock", "Halibut", "Trout", "Mackerel", "Sardines", "Anchovies",
    "Shellfish", "Shrimp", "Prawns", "Crab", "Lobster", "Clams", "Mussels", "Oysters", "Scallops", "Squid",
    "Octopus", "Caviar", "Seaweed", "Kelp", "Nori", "Wakame", "Dulse", "Arame", "Hijiki", "Kombu",
    "Eggs", "Boiled Egg", "Fried Egg", "Scrambled Egg", "Poached Egg", "Omelette", "Deviled Egg", "Egg Salad", "Quiche", "Frittata",
    "Tofu", "Tempeh", "Seitan", "Textured Vegetable Protein", "Soybeans", "Edamame", "Lentils", "Chickpeas", "Black Beans", "Kidney Beans",
    "Pinto Beans", "Navy Beans", "Great Northern Beans", "Cannellini Beans", "Lima Beans", "Fava Beans", "Mung Beans", "Split Peas", "Green Peas", "Snow Peas",
    "Sugar Snap Peas", "Peanut", "Almond", "Walnut", "Pecan", "Cashew", "Pistachio", "Hazelnut", "Macadamia Nut", "Brazil Nut",
    "Chestnut", "Pine Nut", "Sunflower Seed", "Pumpkin Seed", "Sesame Seed", "Chia Seed", "Flaxseed", "Hemp Seed", "Quinoa", "Amaranth",
    "Cereal", "Oatmeal", "Granola", "Cornflakes", "Rice Krispies", "Cheerios", "Frosted Flakes", "Wheaties", "Special K", "Grape-Nuts",
    "Trail Mix", "Energy Bar", "Protein Bar", "Granola Bar", "Fruit Snack", "Fruit Leather", "Fruit Roll-Up", "Popcorn", "Pretzel", "Potato Chips",
    "Tortilla Chips", "Corn Chips", "Pita Chips", "Rice Cakes", "Crackers", "Cheese Puffs", "Cheese Balls", "Veggie Chips", "Fruit Chips"],
  Sports: ["Soccer", "Basketball", "Tennis", "Baseball", "Golf", "Hockey", "Boxing", "Rugby", "Cricket", "Volleyball", "Soccer", "Basketball", "Baseball", "American Football", "Tennis", "Cricket", "Rugby", "Golf", "Ice Hockey", "Volleyball",
  "Table Tennis", "Badminton", "Swimming", "Boxing", "Wrestling", "Martial Arts", "Judo", "Karate", "Taekwondo", "Fencing",
  "Archery", "Shooting", "Cycling", "Mountain Biking", "BMX", "Skateboarding", "Surfing", "Sailing", "Rowing", "Canoeing",
  "Kayaking", "Diving", "Water Polo", "Synchronized Swimming", "Triathlon", "Pentathlon", "Decathlon", "Heptathlon", "Gymnastics", "Rhythmic Gymnastics",
  "Trampoline", "Track and Field", "High Jump", "Long Jump", "Pole Vault", "Shot Put", "Discus Throw", "Hammer Throw", "Javelin Throw", "Race Walking",
  "Marathon", "Sprint", "Hurdles", "Relay Race", "Cross Country", "Snowboarding", "Skiing", "Alpine Skiing", "Nordic Skiing", "Ski Jumping",
  "Biathlon", "Luge", "Bobsleigh", "Skeleton", "Speed Skating", "Figure Skating", "Curling", "Equestrian", "Dressage", "Show Jumping",
  "Eventing", "Horse Racing", "Motorsport", "Formula 1", "NASCAR", "IndyCar", "MotoGP", "Superbike", "Rally", "Drag Racing",
  "Esports", "Chess", "Checkers", "Go", "Backgammon", "Bridge", "Poker", "Billiards", "Snooker", "Pool",
  "Darts", "Bowling", "Lacrosse", "Field Hockey", "Handball", "Netball", "Softball", "Baseball5", "Ultimate Frisbee", "Disc Golf",
  "Parkour", "Freerunning", "Rock Climbing", "Bouldering", "Mountaineering", "Orienteering", "Adventure Racing", "Obstacle Course Racing", "Mud Run", "Tug of War",
  "Sumo Wrestling", "Capoeira", "Muay Thai", "Kickboxing", "Mixed Martial Arts", "Brazilian Jiu-Jitsu", "Sambo", "Savate", "Kendo", "Aikido",
  "Wushu", "Kung Fu", "Pencak Silat", "Glima", "Schwingen", "Kurash", "Bokator", "Lethwei", "Taekkyeon", "Ssireum",
  "Australian Rules Football", "Gaelic Football", "Canadian Football", "Arena Football", "Flag Football", "Touch Football", "Beach Soccer", "Futsal", "Indoor Soccer", "Street Soccer",
  "Roller Hockey", "Inline Hockey", "Street Hockey", "Floorball", "Ball Hockey", "Underwater Hockey", "Underwater Rugby", "Sepak Takraw", "Chinlone", "Bossaball",
  "Kabaddi", "Kho Kho", "Gilli Danda", "Polo", "Elephant Polo", "Camel Racing", "Dog Sled Racing", "Horseball", "Cycle Polo", "Unicycle Hockey",
  "Quidditch", "Hurling", "Camogie", "Shinty", "Bandy", "Ringette", "Broomball", "Ice Stock Sport", "Snow Volleyball", "Snowboarding Cross",
  "Freestyle Skiing", "Mogul Skiing", "Aerial Skiing", "Ski Cross", "Telemark Skiing", "Nordic Combined", "Ski Mountaineering", "Skijoring", "Ice Climbing", "Snowshoeing",
  "Sandboarding", "Land Sailing", "Kite Surfing", "Windsurfing", "Bodyboarding", "Wakeboarding", "Water Skiing", "Jet Skiing", "Flyboarding", "Parasailing",
  "Paragliding", "Hang Gliding", "Base Jumping", "Skydiving", "Wingsuit Flying", "Hot Air Ballooning", "Gliding", "Aerobatics", "Model Aircraft Flying", "Drone Racing",
  "RC Car Racing", "Slot Car Racing", "Soapbox Racing", "Powerboating", "Sailing Yacht Racing", "Dragon Boat Racing", "Canoe Polo", "Rafting", "Stand Up Paddleboarding", "Fishing",
  "Spearfishing", "Free Diving", "Scuba Diving", "Underwater Photography", "Underwater Orienteering", "Underwater Target Shooting", "Underwater Hockey", "Underwater Rugby", "Underwater Archery", "Underwater Wrestling",
  "Underwater Ice Hockey", "Underwater Ice Diving", "Underwater Football", "Underwater Basketball", "Underwater Handball", "Underwater Volleyball", "Underwater Polo", "Underwater Gymnastics", "Underwater Dance", "Underwater Yoga",
  "Underwater Meditation", "Underwater Running", "Underwater Cycling", "Underwater Marathon", "Underwater Triathlon", "Underwater Pentathlon", "Underwater Decathlon", "Underwater Heptathlon", "Underwater Biathlon", "Underwater Obstacle Course",
  "Underwater Relay Race", "Underwater Sprint", "Underwater Hurdles", "Underwater Long Jump", "Underwater High Jump", "Underwater Pole Vault", "Underwater Shot Put", "Underwater Discus Throw", "Underwater Javelin Throw", "Underwater Hammer Throw",
  "Underwater Race Walking", "Underwater Cross Country", "Underwater Orienteering", "Underwater Adventure Racing", "Underwater Parkour", "Underwater Freerunning", "Underwater Rock Climbing", "Underwater Bouldering", "Underwater Mountaineering", "Underwater Obstacle Course Racing",
  "Underwater Mud Run", "Underwater Tug of War", "Underwater Sumo Wrestling", "Underwater Capoeira", "Underwater Muay Thai", "Underwater Kickboxing", "Underwater Mixed Martial Arts", "Underwater Brazilian Jiu-Jitsu", "Underwater Sambo", "Underwater Savate",
  "Underwater Kendo", "Underwater Aikido", "Underwater Wushu", "Underwater Kung Fu", "Underwater Pencak Silat", "Underwater Glima", "Underwater Schwingen", "Underwater Kurash", "Underwater Bokator", "Underwater Lethwei",
  "Underwater Taekkyeon", "Underwater Ssireum", "Underwater Australian Rules Football", "Underwater Gaelic Football", "Underwater Canadian Football", "Underwater Arena Football", "Underwater Flag Football", "Underwater Touch Football", "Underwater Beach Soccer", "Underwater Futsal",
  "Underwater Indoor Soccer", "Underwater Street Soccer"],
  Places: ["Paris", "London", "Tokyo", "Sydney", "New York", "Rome", "Cairo", "Moscow", "Rio", "Toronto", "Eiffel Tower", "Great Wall of China", "Statue of Liberty", "Machu Picchu", "Colosseum",
  "Taj Mahal", "Christ the Redeemer", "Big Ben", "Sydney Opera House", "Mount Fuji",
  "Grand Canyon", "Stonehenge", "Burj Khalifa", "Niagara Falls", "Mount Everest",
  "Acropolis of Athens", "Chichen Itza", "Petra", "Angkor Wat", "Sagrada Familia",
  "Louvre Museum", "Times Square", "Golden Gate Bridge", "Great Barrier Reef", "Buckingham Palace",
  "Mount Kilimanjaro", "Santorini", "Pyramids of Giza", "Alhambra", "Banff National Park",
  "Dubai Marina", "Versailles Palace", "Blue Lagoon", "Victoria Falls", "Uluru",
  "Galápagos Islands", "Hagia Sophia", "Mount Rushmore", "CN Tower", "Table Mountain",
  "Neuschwanstein Castle", "Mount Denali", "Lake Baikal", "Serengeti National Park", "Yellowstone National Park",
  "Yosemite National Park", "Zion National Park", "Grand Teton National Park", "Bryce Canyon National Park", "Arches National Park",
  "Glacier National Park", "Rocky Mountain National Park", "Acadia National Park", "Great Smoky Mountains National Park", "Everglades National Park",
  "Death Valley National Park", "Joshua Tree National Park", "Sequoia National Park", "Olympic National Park", "Mount Rainier National Park",
  "Crater Lake National Park", "Denali National Park", "Banff National Park", "Jasper National Park", "Yoho National Park",
  "Waterton Lakes National Park", "Gros Morne National Park", "Fundy National Park", "Prince Edward Island National Park", "Cape Breton Highlands National Park",
  "Kluane National Park", "Wood Buffalo National Park", "Nahanni National Park", "Auyuittuq National Park", "Sirmilik National Park",
  "Torngat Mountains National Park", "Wapusk National Park", "Iguazu Falls", "Amazon Rainforest", "Patagonia",
  "Atacama Desert", "Salar de Uyuni", "Lake Titicaca", "Easter Island", "Moai Statues",
  "Sydney Harbour", "Great Ocean Road", "Fraser Island", "Whitsunday Islands", "Kakadu National Park",
  "Fiordland National Park", "Milford Sound", "Tongariro National Park", "Rotorua", "Bay of Islands",
  "Bora Bora", "Tahiti", "Moorea", "Palau", "Maldives",
  "Seychelles", "Mauritius", "Reunion Island", "Madagascar", "Zanzibar",
  "Cape Town", "Robben Island", "Kruger National Park", "Victoria & Alfred Waterfront", "Table Mountain",
  "Addo Elephant National Park", "Garden Route", "Drakensberg Mountains", "Lesotho", "Swaziland",
  "Namib Desert", "Etosha National Park", "Okavango Delta", "Chobe National Park", "Hwange National Park",
  "Mana Pools National Park", "Lake Kariba", "Great Zimbabwe Ruins", "Victoria Falls Bridge", "Lake Malawi",
  "Mount Kenya", "Masai Mara", "Amboseli National Park", "Tsavo National Park", "Serengeti National Park",
  "Ngorongoro Crater", "Mount Kilimanjaro", "Zanzibar", "Selous Game Reserve", "Ruaha National Park",
  "Lake Tanganyika", "Lake Victoria", "Rwanda", "Volcanoes National Park", "Nyungwe Forest National Park",
  "Bwindi Impenetrable Forest", "Murchison Falls National Park", "Queen Elizabeth National Park", "Kidepo Valley National Park", "Lake Albert",
  "Sahara Desert", "Pyramids of Giza", "Luxor", "Aswan", "Abu Simbel",
  "Siwa Oasis", "Alexandria", "Cairo", "Nile River", "Red Sea",
  "Petra", "Wadi Rum", "Dead Sea", "Amman", "Jerash",
  "Bethlehem", "Jerusalem", "Tel Aviv", "Haifa", "Nazareth",
  "Masada", "Sea of Galilee", "Golan Heights", "Mount Sinai", "Sharm El Sheikh",
  "Dahab", "Hurghada", "Luxor Temple", "Karnak Temple", "Valley of the Kings",
  "Valley of the Queens", "Temple of Hatshepsut", "Philae Temple", "Kom Ombo Temple", "Edfu Temple",
  "Abu Simbel Temples", "Aswan High Dam", "Lake Nasser", "Nubian Museum", "Unfinished Obelisk",
  "Khartoum", "Meroe Pyramids", "Jebel Barkal", "Dongola", "Kassala",
  "Addis Ababa", "Lalibela", "Axum", "Gondar", "Simien Mountains",
  "Bale Mountains", "Omo Valley", "Lake Tana", "Blue Nile Falls", "Danakil Depression",
  "Djibouti", "Lake Assal", "Tadjoura", "Moucha Island", "Godoria Mangroves",
  "Hargeisa", "Laas Geel", "Berbera", "Mogadishu", "Kismayo",
  "Nairobi", "Mombasa", "Lamu Island", "Mount Kenya", "Lake Nakuru",
  "Lake Naivasha", "Hell's Gate National Park", "Aberdare National Park", "Mount Elgon", "Kakamega Forest",
  "Kisumu", "Lake Victoria", "Jinja", "Entebbe", "Kampala",
  "Lake Bunyonyi", "Rwenzori Mountains", "Semuliki National Park", "Mount Elgon", "Sipi Falls",
  "Kigali", "Lake Kivu", "Nyungwe Forest", "Akagera National Park", "Volcanoes National Park",
  "Gisenyi", "Butare", "Nyanza", "Musanze", "Goma",
  "Kinshasa", "Lubumbashi", "Goma", "Bukavu", "Kisangani",
  "Garamba National Park", "Virunga National Park", "Salonga National Park", "Kahuzi-Biega National Park", "Okapi Wildlife Reserve",
  "Brazzaville", "Pointe-Noire", "Odzala-Kokoua National Park", "Nouabalé-Ndoki National Park", "Conkouati-Douli National Park",
  "Libreville", "Loango National Park", "Ivindo National Park", "Moukalaba-Doudou National Park", "Waka National Park",
  "Lambaréné", "Port Gentil", "Franceville", "Bitam", "Makokou"],
  Celebrities: ["Beyonce", "Drake", "Oprah", "Elon Musk", "Taylor Swift", "Rihanna", "LeBron James", "Adele", "Bill Gates", "Zendaya", "Beyoncé", "Taylor Swift", "Oprah Winfrey", "Elon Musk", "Rihanna", "LeBron James", "Adele", "Bill Gates", "Zendaya", "Dwayne Johnson",
  "Tom Hanks", "Jennifer Lopez", "Barack Obama", "Angelina Jolie", "Brad Pitt", "Lady Gaga", "Justin Bieber", "Kylie Jenner", "Drake", "Emma Watson",
  "Chris Hemsworth", "Kanye West", "Selena Gomez", "Leonardo DiCaprio", "Katy Perry", "Shakira", "Cristiano Ronaldo", "Miley Cyrus", "Ellen DeGeneres", "Ariana Grande",
  "Will Smith", "Kim Kardashian", "Johnny Depp", "Scarlett Johansson", "Justin Timberlake", "Nicki Minaj", "Stephen Curry", "Gigi Hadid", "Ed Sheeran", "Gal Gadot",
  "Michael Jordan", "Reese Witherspoon", "Jennifer Aniston", "Harry Styles", "Meghan Markle", "Prince Harry", "Serena Williams", "Tom Cruise", "Celine Dion", "Chris Evans",
  "Matthew McConaughey", "Blake Lively", "Ryan Reynolds", "Bruno Mars", "Post Malone", "Cardi B", "Shawn Mendes", "Demi Lovato", "Hugh Jackman", "Margot Robbie",
  "Jason Momoa", "Keanu Reeves", "Sofia Vergara", "Kendall Jenner", "Zac Efron", "Lizzo", "Doja Cat", "Billie Eilish", "Timothée Chalamet", "Florence Pugh",
  "Pedro Pascal", "Millie Bobby Brown", "Noah Centineo", "Lili Reinhart", "Cole Sprouse", "Camila Cabello", "Joe Jonas", "Sophie Turner", "Maisie Williams", "Kit Harington",
  "Daniel Radcliffe", "Rupert Grint", "Emma Stone", "Andrew Garfield", "Tom Holland", "Zendaya", "Jacob Elordi", "Sydney Sweeney", "Anya Taylor-Joy", "Jenna Ortega",
  "Paul Rudd", "Chris Pratt", "Vin Diesel", "Gal Gadot", "Henry Cavill", "Ben Affleck", "Robert Pattinson", "Kristen Stewart", "Natalie Portman", "Jake Gyllenhaal",
  "Anne Hathaway", "Meryl Streep", "Viola Davis", "Octavia Spencer", "Regina King", "Angela Bassett", "Lupita Nyong'o", "Chadwick Boseman", "Michael B. Jordan", "Anthony Mackie",
  "Sebastian Stan", "Elizabeth Olsen", "Paul Bettany", "Tom Hiddleston", "Jeremy Renner", "Mark Ruffalo", "Chris Evans", "Chris Hemsworth", "Robert Downey Jr.", "Scarlett Johansson",
  "Samuel L. Jackson", "Don Cheadle", "Brie Larson", "Tessa Thompson", "Letitia Wright", "Danai Gurira", "Florence Pugh", "Hailee Steinfeld", "Oscar Isaac", "Ethan Hawke",
  "Jared Leto", "Margot Robbie", "Will Smith", "Joaquin Phoenix", "Heath Ledger", "Christian Bale", "Michael Keaton", "George Clooney", "Val Kilmer", "Ben Affleck",
  "Robert Pattinson", "Zoe Kravitz", "Paul Dano", "Colin Farrell", "Jeffrey Wright", "Andy Serkis", "Michael Caine", "Gary Oldman", "Morgan Freeman", "Anne Hathaway",
  "Tom Hardy", "Joseph Gordon-Levitt", "Marion Cotillard", "Cillian Murphy", "Ken Watanabe", "Elliot Page", "Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates",
  "Frances McDormand", "Jodie Foster", "Glenn Close", "Sigourney Weaver", "Susan Sarandon", "Julianne Moore", "Nicole Kidman", "Charlize Theron", "Sandra Bullock", "Julia Roberts",
  "Cameron Diaz", "Drew Barrymore", "Reese Witherspoon", "Jennifer Garner", "Jessica Alba", "Eva Mendes", "Salma Hayek", "Penélope Cruz", "Halle Berry", "Lucy Liu",
  "Michelle Yeoh", "Awkwafina", "Constance Wu", "Gemma Chan", "Sandra Oh", "Mindy Kaling", "Priyanka Chopra", "Deepika Padukone", "Aishwarya Rai", "Kareena Kapoor",
  "Shah Rukh Khan", "Aamir Khan", "Salman Khan", "Ranbir Kapoor", "Ranveer Singh", "Hrithik Roshan", "Akshay Kumar", "Ajay Devgn", "Saif Ali Khan", "Varun Dhawan",
  "Alia Bhatt", "Katrina Kaif", "Anushka Sharma", "Jacqueline Fernandez", "Kriti Sanon", "Taapsee Pannu", "Bhumi Pednekar", "Kangana Ranaut", "Radhika Apte", "Nawazuddin Siddiqui",
  "Pankaj Tripathi", "Manoj Bajpayee", "Irrfan Khan", "Naseeruddin Shah", "Om Puri", "Anupam Kher", "Paresh Rawal", "Boman Irani", "Rajkummar Rao", "Ayushmann Khurrana",
  "Vicky Kaushal", "Sidharth Malhotra", "Tiger Shroff", "John Abraham", "Emraan Hashmi", "Arjun Kapoor", "Aditya Roy Kapur", "Shahid Kapoor", "Abhishek Bachchan", "Riteish Deshmukh",
  "Farhan Akhtar", "Karan Johar", "Rohit Shetty", "Sanjay Leela Bhansali", "Anurag Kashyap", "Zoya Akhtar", "Imtiaz Ali", "Kabir Khan", "Rajkumar Hirani", "Rakesh Roshan",
  "Subhash Ghai", "Yash Chopra", "Aditya Chopra", "Karan Malhotra", "Vishal Bhardwaj", "Meghna Gulzar", "Nitesh Tiwari", "Ayan Mukerji", "Ali Abbas Zafar", "Neeraj Pandey",
  "Anurag Basu", "Shoojit Sircar", "Sriram Raghavan", "Vikramaditya Motwane", "Dibakar Banerjee", "Shakun Batra", "Abhishek Kapoor", "Luv Ranjan", "Remo D'Souza", "Prabhu Deva",
  "Farah Khan", "Saroj Khan", "Geeta Kapoor", "Terence Lewis", "Shiamak Davar", "Ganesh Acharya", "Vaibhavi Merchant", "Madhuri Dixit", "Katrina Kaif",
  "Deepika Padukone", "Priyanka Chopra", "Alia Bhatt", "Shraddha Kapoor",],
  Brands: ["Nike", "Apple", "Coca-Cola", "Google", "Amazon", "Pepsi", "Samsung", "Toyota", "McDonald's", "Disney", "Apple", "Microsoft", "Amazon", "Google", "Samsung", "Toyota", "Coca-Cola", "Mercedes-Benz", "McDonald's", "BMW",
  "Louis Vuitton", "Tesla", "Cisco", "Nike", "Instagram", "Disney", "Adobe", "Oracle", "IBM", "SAP",
  "Facebook", "Hermès", "Chanel", "YouTube", "J.P. Morgan", "Verizon", "Nvidia", "Pepsi", "Intel", "Netflix",
  "Visa", "Mastercard", "PayPal", "Uber", "Airbnb", "Starbucks", "LinkedIn", "Spotify", "Red Bull", "L'Oréal",
  "Gucci", "H&M", "Zara", "Uniqlo", "Puma", "Adidas", "Reebok", "Under Armour", "New Balance", "Levi's",
  "Dell", "HP", "Lenovo", "Asus", "Acer", "Panasonic", "Sony", "LG", "Philips", "Toshiba",
  "Huawei", "Xiaomi", "OnePlus", "Oppo", "Vivo", "Motorola", "Nokia", "BlackBerry", "HTC", "Realme",
  "Canon", "Nikon", "Fujifilm", "GoPro", "DJI", "Bose", "Sennheiser", "JBL", "Beats", "Shure",
  "Rolex", "Omega", "Tag Heuer", "Cartier", "Tiffany & Co.", "Pandora", "Swarovski", "Chopard", "Patek Philippe", "Breitling",
  "Burberry", "Prada", "Dior", "Fendi", "Balenciaga", "Givenchy", "Versace", "Armani", "Valentino", "Yves Saint Laurent",
  "Estée Lauder", "Clinique", "MAC", "Sephora", "Maybelline", "Lush", "The Body Shop", "Bath & Body Works", "Neutrogena", "Nivea",
  "Colgate", "Crest", "Oral-B", "Sensodyne", "Listerine", "Dove", "Olay", "Pantene", "Head & Shoulders", "Garnier",
  "Gillette", "Schick", "Venus", "Bic", "Old Spice", "Axe", "Degree", "Secret", "Speed Stick", "Right Guard",
  "Kellogg's", "General Mills", "Nestlé", "Unilever", "Procter & Gamble", "Johnson & Johnson", "PepsiCo", "The Coca-Cola Company", "Mondelez", "Mars",
  "Hershey's", "Ferrero", "Lindt", "Godiva", "Cadbury", "Toblerone", "KitKat", "Snickers", "M&M's", "Skittles",
  "Lay's", "Doritos", "Pringles", "Cheetos", "Ruffles", "Frito-Lay", "Tostitos", "SunChips", "Bugles", "Popchips",
  "Ben & Jerry's", "Haagen-Dazs", "Breyers", "Blue Bell", "Magnum", "Klondike", "Dairy Queen", "Cold Stone Creamery", "Baskin-Robbins", "Carvel",
  "Domino's", "Pizza Hut", "Papa John's", "Little Caesars", "California Pizza Kitchen", "Chuck E. Cheese", "Sbarro", "Marco's Pizza", "Jet's Pizza", "Hungry Howie's",
  "Subway", "Jimmy John's", "Jersey Mike's", "Firehouse Subs", "Quiznos", "Panera Bread", "Au Bon Pain", "Pret A Manger", "Schlotzsky's", "Which Wich",
  "KFC", "Popeyes", "Chick-fil-A", "Raising Cane's", "Church's Chicken", "Bojangles", "El Pollo Loco", "Zaxby's", "Wingstop", "Buffalo Wild Wings",
  "Taco Bell", "Chipotle", "Del Taco", "Qdoba", "Moe's Southwest Grill", "Baja Fresh", "Freebirds", "Taco John's", "Rubio's", "Chronic Tacos",
  "Wendy's", "Burger King", "Five Guys", "In-N-Out Burger", "Shake Shack", "Culver's", "Whataburger", "Smashburger", "Hardee's", "Carl's Jr.",
  "Arby's", "Sonic Drive-In", "Jack in the Box", "Checkers", "Rally's", "Steak 'n Shake", "Freddy's", "White Castle", "Krystal", "A&W Restaurants",
  "Dunkin'", "Starbucks", "Peet's Coffee", "Caribou Coffee", "Tim Hortons", "Dutch Bros", "Biggby Coffee", "The Coffee Bean & Tea Leaf", "Gloria Jean's Coffees", "Seattle's Best Coffee",
  "7-Eleven", "Circle K", "Wawa", "QuikTrip", "Sheetz", "RaceTrac", "Casey's", "Speedway", "Love's", "Pilot Flying J",
  "Costco", "Sam's Club", "BJ's Wholesale Club", "Walmart", "Target", "Kmart", "Sears", "Macy's", "Nordstrom", "JCPenney",
  "Kohl's", "Dillard's", "Belk", "Neiman Marcus", "Saks Fifth Avenue", "Bloomingdale's", "Lord & Taylor", "Barneys New York", "Bergdorf Goodman", "Von Maur",
  "Best Buy", "GameStop", "Micro Center", "B&H Photo", "Newegg", "Fry's Electronics", "TigerDirect", "CompUSA", "Circuit City", "RadioShack",
  "Home Depot", "Lowe's", "Menards", "Ace Hardware", "True Value", "Harbor Freight Tools", "Northern Tool", "Grainger", "Fastenal", "Snap-on",
  "IKEA", "Ashley Furniture", "Rooms To Go", "La-Z-Boy", "Havertys", "Ethan Allen", "Crate & Barrel", "Pottery Barn", "West Elm", "Restoration Hardware",
  "Wayfair", "Overstock", "Hayneedle", "AllModern", "Joss & Main", "Birch Lane", "Z Gallerie", "CB2", "World Market", "Pier 1 Imports",
  "Amazon", "eBay", "Alibaba", "Rakuten", "Etsy", "Shopify", "Walmart", "Target", "Best Buy", "Newegg",
  "UPS", "FedEx", "DHL", "USPS", "Canada Post", "Royal Mail", "Australia Post", "Deutsche Post", "La Poste", "Japan Post",
  "China Post", "India Post", "Singapore Post", "Hongkong Post", "PostNL", "Correos", "Poste Italiane", "Swiss Post", "PostNord",
  "TNT Express", "YRC Freight", "Old Dominion Freight Line", "XPO Logistics", "C.H. Robinson", "J.B. Hunt Transport Services", "Schneider National", "Werner Enterprises", "Swift Transportation"],
};
